google/osv-scanner

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go
I've not yet added any test cases for the exit code when vulnerabilities are present because that requires having a lockfile with a vulnerability (which'll annoy dependabot) and interacting with the production API (which'll be relatively slow, the OSV could change, etc) - I plan to address that by adding a flag to set the API URL which'll allow leveraging [`httptest`](https://pkg.go.dev/net/http/httptest) like what I do in `osv-detector` [for testing the API-based databases](https://github.com/G-Rath/osv-detector/blob/main/pkg/database/api-check_test.go#L139-L153).
As for the error codes themselves, I've effectively split the 0-255 range in half (rounded down) with the upper half (starting at 127, as "general error") being reserved for "non-results related errors" such as files not found, …
=> fix: set error codes differently based on if there are vulnerabilities present

pkg/config/config.go, pkg/osvscanner/vulnerability_result.go
Missing a line in the result grouping code that caused the git vulnerabilities to not actually be reported.
=> Fix git commit result reporting

cmd/osv-scanner/main.go, internal/osv/osv.go, pkg/config/config.go, pkg/osvscanner/osvscanner.go
The error messages were not following the convention established for Go: [Convention](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)
=> fix: change error strings to golang convention

pkg/lockfile/fixtures/go/replace-different.mod, pkg/lockfile/fixtures/go/replace-local.mod, pkg/lockfile/fixtures/go/replace-many.mod, pkg/lockfile/fixtures/go/replace-mixed.mod, pkg/lockfile/fixtures/go/replace-no-version.mod, pkg/lockfile/fixtures/go/replace-not-required.mod, pkg/lockfile/fixtures/go/replace-one.mod, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go
Resolves #30
In theory this adds support for `replace`, though in practice it's only going to be useful when the replacement package is remote because there's no way to resolve the local package to the corresponding remote package name that'll be in OSVs - it's tempting to try and infer that from the target (e.g. if you're replacing `golang.org/x/net` with `./fork/net`, then it could be reasonable to assume its a fork of `golang.org/x/net`) but in practice there's no way to know when that shouldn't be applied either.
Likewise for the version, if there isn't one set as part of the replacement then there's not really anything that can be done because there's no requirement from Go that a version be specified for the replacement package anywhere on disk - the best that could be done would be …
=> fix: include `replace` directives in `go.mod`

.goreleaser.yml
Tested and working though the output is a bit rough: 
A release would look like this: https://github.com/another-rex/osv-scanner/releases/tag/v0.1.4
=> Fix go releaser

cmd/osv-scanner/main.go
Currently a nil pointer exception appears when passing in unknown flags.
=> Fix minor bug when passing in unknown flags

cmd/osv-scanner/main.go
The version command was missing, as mentioned in this [issue](https://github.com/google/osv-scanner/issues/42).
The goreleaser already setting build information here: https://github.com/google/osv-scanner/blob/e5f1dc67baff39c840963a5966219f81e2c7fe76/.goreleaser.yml#L14-L16, to take advantage of this I implemented this feature based on this information.
The "urfave/cli" already has a clean way to implement this feature, as mentioned here: https://cli.urfave.org/v2/examples/version-flag/
=> feat: add version command

.goreleaser.yml
Tested locally emulating aarch64 and it ran successfully. Scorecard also supports aarch64. Fixes #49
=> Enable arm64 build target

.github/workflows/codeql-analysis.yml, .github/workflows/goreleaser.yml, .github/workflows/lint.yaml, .github/workflows/scorecards.yml, renovate.json, run_lints.sh, run_tests.sh
- use git hashes instead of tags and update to latest
- format json and udpate .sh files
=> Ci updates

README.md
The anchor link to Scanning a Debian based docker image packages was broken.
=> Fix readme anchor link.

README.md
This PR adds installation instructions for using Scoop on Windows (https://github.com/ScoopInstaller/Main/pull/4231) which should make it nice and easy for anyone on a Windows machine to use this.
=> Added installation instructions for Scoop

internal/output/table.go
(and last to get cropped
Also only do unicode output when printing to terminal, otherwise print default ascii when being piped to file or piped to a pager. 
Partially fixes #85
=> Move table columns so that the important column is displayed first

README.md
Corrects the osv-scanner command example for scanning lockfiles to use consistent command line flags.
Using mixed `--lockfile` and `-L` options in the same command (as shown in example) results in a `Can't use two forms of same flag: L lockfile` error.
=> Fix lockfile command example flags

pkg/config/config.go, pkg/lockfile/csv.go, pkg/lockfile/parse-gradle-lock.go, pkg/osvscanner/osvscanner.go
Noticed by @cmaritan on #105 - so far I've not been able to reproduce the error, but it's still good practice to be calling `file.Close` otherwise they won't get closed until GC next runs which could be a while.
I've also done a slight refactor of variable names for consistency.
=> fix: ensure that files are closed when they're no longer needed

pkg/lockfile/parse_test.go
Realised this hadn't been updated while porting some stuff back to `osv-detector`
=> test: update spec case and adjust assertion message

renovate.json
Use the same PR labelling strategy we're using the osv.dev repo.
=> Have renovate-bot label its PRs as it does with osv.dev

.github/workflows/lint.yaml
Which results in lint checks on the main branch after the PR has been merged.
=> Make lint trigger same as codeql

README.md
I would suggest to document the release process, and in particular how to reproduce the builds locally.
=> docs: describe build process

go.mod, go.sum, internal/output/table.go
When I ran osv-scanner in my repo, I got the following output:
This looked weird for me since the entire lower half of table is highlighted including borders. I reported this at https://github.com/jedib0t/go-pretty/issues/248 and the maintainer kindly added an option for this.
This PR avoids highlighting borders of the table using the option. Now the output looks like below:
This looks better for me because it is clear that only the row is highlighted.
The `DoNotColorBordersAndSeparators` option requires the latest version of `go-pretty` so I updated the version in `go.mod` and `go.sum` (this was very small update from v6.4.3 to v6.4.4). I ran all tests with `run_tests.sh` and confirmed they passed successfully.
=> Do not highlight borders of result table

internal/osv/osv.go
Use short url in scanner output.
```
╭─────────────────────────────────────┬───────────┬──────────────────────────────┬─────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────╮
│ OSV URL (ID IN BOLD)                │ ECOSYSTEM │ PACKAGE                      │ VERSION                             │ SOURCE                                                                               │
├─────────────────────────────────────┼───────────┼──────────────────────────────┼─────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ https://osv.dev/RUSTSEC-2021-0145   │ crates.io │ atty                         │ 0.2.14                              │ ..       │
│ …
```
=> Use short url in scanner output

pkg/lockfile/parse-nuget-lock.go
There's a Go convention with comments to start them with the name of the type/func/etc which GoLand checks for by default - afaik this isn't strictly a rule being followed in this repo, but this particular comment is only off by a single char so might as well make GoLand happy 😅
=> chore: adjust comment to match type name

internal/osv/osv.go
Fix endpoint typo.  We should have some automated integration tests to catch this in the future.
=> Fix endpoint typo

README.md, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, internal/output/reporter.go
Helps with #156 and [related to](https://github.com/google/osv-scanner/issues/85#issuecomment-1361890538) #85.
I've gone with `--format` instead of `--output` because it seems more common (looking at CLI tools like ESLint, Rubocop, `bundler-audit`, rspec, Terminus) and also because `--output` tends to match the flag used by some CLI tools for "output to file" such as ESLint and cURL which the scanner might decide to support one day.
I've also kept it simple for now since there's only a couple of formats supported - in future it might make sense to employ enum / const types and look at some fancy map similar to what `lockfile` has for its parsers, but I don't think that's needed here yet.
(this'll need rebasing when #161 is landed)
=> feat: create `--format` flag

cmd/osv-scanner/main.go
Because `VersionPrinter` is a global, everytime `run` is called that function is set to use whatever
the latest call to `run` was passed for `stdout` and `stderr`; while this shouldn't ever be a
problem when running the scanner from the commandline (because that'll only call `run` once), the
test suite calls `run` many times in parallel with different `stdout` and `stderr` writes each time
so there's a very small chance that by the time the `--version` test actually ends up calling the
`VersionPrinter` it's been set to a new function using the `stdout` and `stderr` of a _different_
test causing it to fail.
We can fix this by having the `VersionPrinter` use the `Writer` and `ErrWriter` writers that have been passed to the `App`, which will always be the right `stdout` and `stderr` writers …
=> fix: reuse app-level writer and err writers in `VersionPrinter`

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, internal/output/reporter.go
Addresses something I noticed in #94 - I was expecting it to require more hoop jumping but realised this should be a pretty robust/correct solution.
Right now there is only one primary cases where an error is printed but the actual error does not result in the function bailing out, though this will be expanded a little by the changes in #94.
(this'll need rebasing when #158 is landed)
=> fix: exit with generic non-zero code when there is a general error

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, internal/output/markdowntable.go, internal/output/reporter.go, internal/output/table.go
Add a `--markdown` command line switch that will render the output table as a markdown table for use when making comments to github and other places that use markdown.
Resolves #61
Here's what the output looks like for `osv-scanner -D golang:1.18-rc-stretch --format markdown`:
```
Scanned docker image with 189 packages
| OSV URL | Ecosystem | Package | Version | Source |
| --- | --- | --- | --- | --- |
| https://osv.dev/DLA-2948-1 | Debian | debian-archive-keyring | 2017.5+deb9u1 | golang:1.18-rc-stretch |
| https://osv.dev/DLA-3022-1 | Debian | dpkg | 1.18.25 | golang:1.18-rc-stretch |
| https://osv.dev/DLA-2952-1 | Debian | openssl | 1.1.0l-1~deb9u4 | golang:1.18-rc-stretch |
| https://osv.dev/DLA-3008-1 | Debian | openssl | 1.1.0l-1~deb9u4 | golang:1.18-rc-stretch |
| …
```
=> feat: Render output as a markdown table for use in github comments

pkg/lockfile/parse-cargo-lock_test.go, pkg/lockfile/parse-gemfile-lock_test.go, pkg/lockfile/parse-poetry-lock_test.go
`Gemfile.lock` is nothing close to JSON, so this test doesn't make sense - removing it does not decrease coverage either, so lets axe it.
My best guess is that it came from copying the standard set of tests from one of the other parsers, and then not realising it since it never failed 🤷 
I also noticed two test cases were incorrectly named "json" instead of "toml", so have corrected that too
=> test: remove nonsense case and correct names

pkg/osv/osv.go
Resolve #184 (if `models.SourceInfo` is confirmed to be unneeded!)
=> fix(osv-query): omit SourceInfo from JSON marshaling

.github/workflows/lint.yaml, pkg/config/config.go, run_lints.sh
I was curious and ended up doing the work so might as well land it 🤷
This also removes one of the three "<linter> is disabled because generics" warnings.
=> fix: add missing toml tags to struct (and update linter)

USAGE.md, pkg/osvscanner/osvscanner.go
I had thought of some minor improvements for the gitignore parsing I had implemented:
- Parse gitignores for non-git files from their respective directories, instead of the current working directory.
- Should fix #202, and I think also a potential issue on Windows scanning across drive letters.
- Fix some error messages not having newlines.
- Add a error message warning if the root file is ignored, instead of skipping silently.
- Add some notes in USAGE.md about gitignore behaviour.
=> Improve gitignore parsing

docs/_config.yml
The Link to the osv.dev docs was broken. ([osv.dev/docs](https://osv.dev/docs) gets a 404 but [osv.dev/docs/](https://osv.dev/docs/) works ok. Thanks to Kara for the catch.
=> fixed broken link

docs/current/configuration.md, docs/current/installation.md, docs/current/output.md, docs/current/usage.md, docs/working_docs/configuration.md, docs/working_docs/installation.md, docs/working_docs/output.md, docs/working_docs/usage.md
Hi Team, 
Based on post-merge feedback on #211 , styling has been updated to use bash formatting in most places, and json and toml where appropriate. 
Some of the text colors do not have good contrast. I will continue working on that as time permits, with the hope to roll it out to other projects too but this can be merged now. 
You can see what it looks like [here](https://hayleycd.github.io/osv-scanner/)
=> Reinstated Bash Formatting

docs/_config.yml
Changes can be previewed [here](https://hayleycd.github.io/osv-scanner/). 
I was given a tracking ID and assumed it was in the format of google analytics 4. I checked the site's HTML and it seems to be enabled, but someone might want to check the dashboard.
=> Google analytics added.

pkg/lockfile/apk-installed.go
Hello,
ported to APK installed parser common optimizations already merged for DPKG in #168.
Additionally, a couple of staticcheck linter errors have been corrected (I think!).
I saw the comments here: https://github.com/google/osv-scanner/blob/fb4d2c4d8e4e59961db70121e31870593e045a4e/pkg/osvscanner/osvscanner.go#L39-L43 but after my change both lints and tests are ok so it's not clear to me if comments are now out of date or if I'm missing something!
Comments have been introduced in #149.
Thank you,
Regards.
=> Nits  - APK installed optimizations

pkg/lockfile/apk-installed_test.go, pkg/lockfile/dpkg-status_test.go
Typically test functions should start with the function under test (or at least that's the convention I've used for the rest of the tests in `lockfile`).
=> test: ensure case names match function under test

.goreleaser.yml
Create draft release first for future releases instead of a full release so release details can be edited before the email is sent out to watchers.
=> Create draft release first in goreleaser

cmd/osv-scanner/fixtures/locks-many/alpine.cdx.xml, cmd/osv-scanner/fixtures/sbom-insecure/postgres-stretch.cdx.xml, cmd/osv-scanner/main_test.go, internal/sbom/cyclonedx.go, internal/sbom/sbom.go, internal/sbom/spdx.go, pkg/osvscanner/osvscanner.go
Make sure the file name follows the recognized file names here: https://cyclonedx.org/specification/overview/#recognized-file-patterns
Resolves #257 
Also 
- adds tests for sboms,
- makes SBOM scan logging output consistent with lockfile scan logging output
- Minor refactor of SBOMs
I believe we will also want something similar to parse-as in lockfiles for SBOMs as well in the future to allow file names that doesn't conform to the standard to be scanned.
=> More specific cyclone dx parsing

pkg/lockfile/fixtures/pnpm/files.yaml, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pnpm-lock_test.go
=> fix: avoid panic when parsing `file:` dependencies in `pnpm` lockfiles

cmd/osv-scanner/main_test.go
CI is failing because this advisory is now present
=> test: update case with new advisory

docs/installation.md, docs/output.md, docs/usage.md
Adding call graph stuff back in now the current docs are on the docs branch.
=> Adding call graph info back in

internal/semantic/fixtures/maven-versions.txt, internal/semantic/version-maven.go
This was found in the latest version of the generated maven versions fixture - I'm pretty sure this also is present in the API version too as it's also missing kind of function, but I've not tested that for sure.
I've not updated the generated fixture because I'm going to be following this up with a new generator workflow that will involve that, but this needs to be landed first otherwise _that_ PR will fail CI 😅
=> fix: trim leading zeros off when comparing numerical components in Maven versions

renovate.json
Because govulncheckvulns has now been updated to remove the API vulncheck API, but haven't added a new API yet. Remove this once new API is ready.
=> Renovate bot ignore vulns package

pkg/osvscanner/osvscanner.go
This is also probably where having a verbosity level when reporting could be useful. By default we probably would not want to print out every invalid PURL, but this could be helpful if someone wants to find what invalid PURLs they have in their SBOM.
=> Check if PURL is valid before adding it to queries

pkg/lockfile/fixtures/maven/invalid-syntax.xml, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
=> fix: avoid infinite loops parsing Maven poms with syntax errors

internal/semantic/version-maven.go
While the fix I landed in https://github.com/google/osv-scanner/pull/279 was a fix, it wasn't the _best_ fix - really the bug was I'd used the wrong variable - @michaelkedar comment about [these tests](https://github.com/google/osv-scanner/pull/279#pullrequestreview-1334066731) catching this is the key (they pass because the whole string can be parsed as a number, meaning the incorrect condition is passing)
=> fix: trim leading zeros off when comparing numerical components in Maven versions (better)

cmd/osv-scanner/main_test.go
Should fix #286.
The issue was that the tests were expecting osv-scanner to be a git repository, and the downloading the GitHub release source files does not include the `.git` directory.
Fixed by initializing the `fixtures` directory as a git repository when running the tests, which both prevents git from walking past the folder, and parses the `.gitignore` files for the related test.
=> Prevent `.gitignore` files from interfering with tests

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go
Set the release version in the source code. 
An alternative to setting the version directly in source code is to get package repositories to build their osv-scanner with goreleaser instead of go directly. While goreleaser is often already in most repositories, it is not as straightforward:
- Package repositories sometimes have their own guidelines for how to build go, e.g. Arch Linux go binaries must be built with hardened options which we currently do not do with goreleaser.
- goreleaser also expects to be in a git repository (to get version tags), but most build systems prefers downloading the source code in a tarball instead of checking out the repository.
=> Set version in source code

pkg/lockfile/fixtures/pipenv/no-version.json, pkg/lockfile/parse-pipenv-lock.go
This extracts the shared detail parsing between default and develop packages.
Resolves #296
=> fix: support Pipenv develop packages without versions.

go.mod, go.sum, pkg/osv/osv.go
An attempt at concurrency for hydration requests. I'm not sure if this is the most concise way to do so, it seems pretty long for what should be a simple concurrency logic.
=> Adds concurrency to hydration requests

internal/govulncheckshim/fixtures/snapshots/govulncheckshim_test.json, pkg/models/constants.go, pkg/models/results.go, pkg/models/vulnerability.go
- splits the models into separate structs
- defines a bunch of constants
- adds Credit and Severity types
=> Improve the OSV models to allow for 3rd party use of the library.

internal/sbom/cyclonedx.go, internal/sbom/cyclonedx_test.go, internal/sbom/fixtures/cyclonedx-empty.json, internal/sbom/fixtures/cyclonedx.json
=> Add nil check to cyclonedx enumeration

.github/workflows/lint-action/action.yml
This occassionally causes issues for our linter like: https://github.com/google/osv-scanner/actions/runs/4675534898
See https://github.com/golangci/golangci-lint-action/issues/135.
=> Set `skip-pkg-cache: true` for golangci-lint

cmd/osv-scanner/main.go, internal/sourceanalysis/go.go, internal/sourceanalysis/sourceanalysis.go, pkg/config/config.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/osvscanner_internal_test.go, pkg/osvscanner/vulnerability_result.go, pkg/osvscanner/vulnerability_result_internal_test.go, pkg/reporter/reporter.go
Make the reporter package public so that it can be passed into the public DoScan function.
=> Make the reporter public

.github/workflows/lint-action/action.yml, internal/sbom/cyclonedx.go, internal/sbom/sbom.go, internal/sbom/spdx.go, pkg/osvscanner/osvscanner.go
Addresses part of #335
1. Be more relaxed about filename matching the spec when the SBOM is explicitly passed via --sbom since we've seen multiple complaints from different users about this.
2. Surface all parse errors when SBOM parsing fails (and we're explicitly scanning via --sbom).
This will look something like:
```
Failed to parse SBOM using all supported formats:
failed to parse SPDX:
failed trying json: failed to parse Supplier 'Google LLC'
failed trying rdf: found extra chars before tag start
failed trying tv: no colon found in '{'
failed to parse CycloneDX:
failed trying json: invalid BOMFormat
failed trying xml: XML syntax error on line 74: expected attribute name in element
No package sources found, --help for usage information.
exit status 128
```
=> SBOM parsing improvements.

docs/usage.md, internal/sbom/cyclonedx.go, internal/sbom/sbom.go, internal/sbom/spdx.go, pkg/osvscanner/osvscanner.go
Closes #335 #290 #93 #347 (Turns out we have a bunch of duplicate issues all roughly tracking the same thing)
=> Better SBOM documentation and error message

pkg/osvscanner/osvscanner.go
Bug in sbom scanning code to quit immediately after successfully parsing but not finding any packages, rather than trying all formats.
=> Fix sbom scanning code

pkg/osv/osv.go
I don't know if you all intended `pkg/osv` to be a general purpose https://osv.dev/ client library, but we are using it as that here: https://github.com/guacsec/guac/blob/main/pkg/certifier/osv/osv.go
It would be nice to override the http client used to insert custom transports, etc.
=> Update pkg/osv to allow overriding the http client / transport.

docs/configuration.md, docs/contribute.md, docs/installation.md, docs/output.md, docs/usage.md
There were some inconsistencies in the documentation headings. 
I also added navigation to the usage page because it was getting a bit unwieldy. 
[Preview here](https://hayleycd.github.io/osv-scanner/usage/)
=> Small formatting changes

pkg/lockfile/fixtures/pip/line-continuation.txt, pkg/lockfile/fixtures/pip/with-hash.txt, pkg/lockfile/fixtures/pip/with-per-requirement-options.txt, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
This removes everything after the whitespace of the version to also
catch the other per-requirement options --global-option and
--config-settings and any future options that may be added
https://pip.pypa.io/en/stable/reference/requirements-file-format/#per-requirement-options
fixes: https://github.com/google/osv-scanner/issues/369
While addressing this i noticed the pip documentation example for --hash
used line continuations which weren't currently supported by this parser
so i've added support for this
=> Remove --hash from version in requirements.txt

.github/workflows/goreleaser.yml
With #383 merged, we can now resolve #317 
Slightly difficult to test in a separate repository as the goreleaser things are not set up there with the correct permissions, so let's test on wednesday with the release.
=> Use upload draft assets option

docs/_sass/color_schemes/better_contrast.scss
I think there was an update to our jekyll theme and it no longer accepts "px" units in the css. So I removed a line so it can build.
=> Fixing broken github page

pkg/models/vulnerability.go, pkg/models/vulnerability_test.go
- withdrawn timestamp does not exist in the model - add it to the model.
- fix the timestamp serialization to ensure published and withdrawn are *only* present when the value is not zero
- fix timestamp serialization to use RFC3339 for JSON (it uses RFC3339Nano by default)
- fix the timestamps to be normalized to UTC as per the schema
=> Add withdrawn and fix time serialization to conform to the schema.

cmd/osv-scanner/main_test.go
Currently if the test suite is exited prematurely by a ctrl+c or if it runs badly such as due to invalid flags being passed, it'll not properly do its cleanup - this'll then cause the suite to fail with a panic until the `.git` directory is manually removed from `.cmd/osv-scanner/fixtures`.
=> test: ensure fixtures directory isn't already a git repository

.github/workflows/link-check-on-push.yml, .github/workflows/link-check.yml
This PR does the following:
Pins the action to a commit.
Changes scheduled scanning to twice a week.
=> Adjusting GitHub actions

renovate.json
Same as https://github.com/google/osv.dev/pull/1505
Confirmed that it works as expected in osv.dev repository.
> Dependabot often has updates that don't show up in renovate bot. That's because renovatebot doesn't directly update any transient dependencies. 
> 
> Enabling this option instructs renovatebot to relock the lockfiles, which will bump all transient dependencies. See https://docs.renovatebot.com/configuration-options/#lockfilemaintenance and https://github.com/renovatebot/renovate/discussions/15762
=> Enable lockfile maintaince

internal/output/sarif_test.go
This is good practice since you shouldn't be testing the private internals of a package, even if its a private package
=> test: make `output` tests their own package

cmd/osv-scanner/fixtures/sbom-insecure/alpine.cdx.xml, cmd/osv-scanner/fixtures/sbom-insecure/osv-scanner.toml, cmd/osv-scanner/main_test.go, pkg/models/purl_to_package.go, pkg/models/purl_to_package_test.go
Parsing PURL to OSV-Scanner ecosystems was not accurate for alpine, and would be not accurate for future conversions when we add additional ecosystems.
This PR adds a test for alpine, and also fixes/future proofs the PURL mapping.
(This should also be a good test for the newly merged osv-scanner action. I haven't added in the osv-scanner.toml ignore file for the new alpine vuln, so it should prevent us from merging)
=> Fix purl mapping

cmd/osv-scanner/main.go, pkg/osvscanner/osvscanner.go
This pulls across the experimental struct from #183 which I'm assuming folks are happy with given that PR is approved - I think it is good to land this in its own PR as its technically an allowed breaking change (or "experimental change" if you will), and that way it can be explicitly linked to in changelogs etc without having to understand #183 as much.
=> refactor: move experimental flags into their own struct

.github/workflows/osv-scanner-scheduled.yml, .golangci.yaml, pkg/osvscanner/optional_enricher.go, pkg/osvscanner/osvscanner.go
Fixes #453,
As discussed in #453, it does require go to be installed on the system that osv-scanner is being ran on. The go installation can be at a custom location as long as $GOROOT environment var is specified.
Also exclude the depguard check, which has been added in a newer version of golangci (which we haven't updated to, but will cause linting issues when we eventually do).
=> Add go stdlib version support

pkg/osvscanner/optional_enricher.go
If go version can't be found, don't add stdlib to the parsed packages.
=> If go version can't be found, don't add stdlib

internal/local/check.go, pkg/lockfile/extractor.go, pkg/osv/osv.go, pkg/osvscanner/vulnerability_result.go
Changing the type of Package.Ecosystem would be a breaking change, so revert that back to string. Doesn't affect too much so looks fine to me, let's add this to #442 for V2.
Also changed `Response.Vulns` back to type `[]models.Vulnerability`. I don't think this changes anything since go coerces the types to each other when setting the value.
And made the not supported error a bit more specific
=> Revert breaking change in `osv.go`

cmd/osv-scanner/main_test.go
CVE-2022-37434 was updated with a new CVSS score, and main_test needs to be updated.
=> Update test results to pass new test

.github/workflows/test-action/action.yml, .gitignore, CONTRIBUTING.md, run_tests.sh
This is a real basic starter for 10 - I considered doing something more fancy with `run_tests.sh` but realised it would just be better to discuss the general approach to scripts for the scanner as its own thing (i.e. we could use `make`, we could move things into `scripts`, we could just have multiple scripts for things...) so for now have just made coverage collection always enabled and documented how to generate the HTML report.
~I have also included uploading the results to codecov but ultimately that's for Google folks to decide what they want to do - if folks are happy to use codecov I think this can be merged as is and it'll just automatically create the project etc and you should be able to access that via logging in with GitHub.~ Whoops I didn't think about the actions running for …
=> chore: capture coverage and upload it to codecov

internal/local/check.go, internal/output/table.go, pkg/lockfile/fixtures/osvscannerresults/one-package-commit.json, pkg/lockfile/osv-vuln-result_test.go, pkg/lockfile/osv-vuln-results.go, pkg/models/results.go, pkg/osv/osv.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go
Fix issues with scanning OSV-Scanner Results.
- Adds support for adding commit hashes to the OSV-Scanner results, 
- Allow actually scanning OSV-Scanner results from the cli.
=> Fix result scanning

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-reusable-pr.yml, .github/workflows/osv-scanner-reusable-scheduled.yml, .github/workflows/osv-scanner-scheduled.yml
- Fix missing the ./ in the scheduled scan. 
- Fix passing gh-annotations correctly
- Update naming of the actions to be more clear
=> Fix action naming and scheduled scan parameters

internal/local/zip_test.go
This isn't hiding anything, but it's semantically incorrect
=> test: compare expected with actual rather than the other way around

cmd/osv-scanner/main_test.go
This makes it easier to determine what is wrong in CLI tests by showing an actual diff; while in most cases this is an improvement, I have found it's sometimes useful to have the raw output printed so I've included an env variable to allow switching easily with `cmp.Diff` being the default.
In order to reduce the diff noise when a test does fail, this also switches to replacing occurrences of the current working directory in the _actual_ output with `<rootdir>`; this also means that the output will be what should be in the test cases, rather than the absolute path that people would have to replace with `<rootdir>`.
While this could be used throughout the whole test suite, I've just applied this to the CLI tests for now because I think they've got the most to gain whereas it'd be a lot of …
=> test: use `cmp.Diff` for comparing output

.github/workflows/checks.yml, .github/workflows/goreleaser.yml
The test suite needs to be adjusted to handle OS-based differences before it can be run on Windows, but in the meantime we can start running on macOS; this also moves the linting step to be in parallel when releasing too.
=> ci: run tests on macos and in parallel when releasing

.github/workflows/goreleaser.yml, .github/workflows/osv-scanner-reusable.yml, .github/workflows/osv-scanner-scheduled.yml, docs/github-action.md
`osv-scanner-reusable-scheduled` actually doesn't have anything to do with having a schedule, so just removed the scheduled part from the name. 
This reusable workflow is now also used in the release pipeline to block releases if there are vulnerabilities.
=> Block release on vuln scan

.github/workflows/link-check-on-push.yml, .github/workflows/link-check.yml, .github/workflows/osv-scanner-reusable-pr.yml
I'm surprised that renovate didn't flag these but oh well 🤷
=> ci: ensure that `actions/checkout` is pinned

.github/workflows/checks.yml, .github/workflows/goreleaser.yml
These jobs shouldn't need the whole commit history, so this is just wasting CPU cycles
=> ci: don't fetch the whole repository history when its not needed

.github/workflows/goreleaser.yml
Testing these fixes per merge, it runs correctly now, just need permission to upload the scan SARIF results.
=> Allow release scanning to upload SARIF file. 

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-scheduled.yml
Make scheduled and PR scanning only scan the relevant files and ignore fixtures. This prevents us from constantly having to add ignores for new vulnerabilities, and it polluting the output.
We still need to add new vulns to the tests though.
=> Make scheduled and PR scanning only scan the relevant files and ignore fixtures

cmd/osv-scanner/main_test.go, internal/output/fixtures/test-vuln-results-a.sarif, internal/output/sarif.go
=> Add name field to sarif rule output

.github/workflows/goreleaser.yml
Update the release pipeline to have it be manually triggered, and create a tag itself if checks and scans are successful.
It looks something like this:
The release doc has been updated to follow this new workflow.
=> Update release pipeline

go.mod, go.sum, internal/testutility/utility.go
I think this gives an overall better output, and it lets us drop a couple of dependencies
Before:
After:
=> test: use `cmp.Diff` for diffing

.github/workflows/goreleaser.yml, docs/Gemfile, docs/github-action.md
- Fix github action documentation to have correct examples
- Update jekyll feed dependency, which renovate bot fails to do for some reason
- Set the upload-tag-name to actually upload the verification along with the release using the new pipeline. (This is because the new pipeline no longer runs "on" a commit, so cannot automatically pick up the tag. This actually causes bigger problems in that we can't verify the tag (see https://github.com/slsa-framework/slsa-github-generator/issues/1947))
=> Some minor post release fixes

pkg/osvscanner/optional_enricher.go
as it's very likely to be found in a lot of circumstances (e.g. running in CI).
See #620 for more context.
=> Go binary not found should not be an error

pkg/osvscanner/osvscanner.go
Was representing the relative root of the repo as `./.` which, if the .gitignore file matched `.*`, caused the whole directory to be ignored.
=> Fix gitignore matching for root directory

pkg/osv/osv.go, pkg/osvscanner/osvscanner.go
Fixes #612.
Tested on https://github.com/opencv/opencv
We need to set up an e2e test for this as well (maybe add some submodules + vendored libs to https://github.com/ossf-tests/scorecard-check-osv-e2e).
```
Scanning dir /tmp/opencv
Scanning /tmp/opencv/ at commit e9e6b1e22c1a966a81aca1217b16a51fe7311b3b
Scanning directory for vendored libs: /tmp/opencv/3rdparty
Scanning potential vendored dir: /tmp/opencv/3rdparty/carotene
Scanning potential vendored dir: /tmp/opencv/3rdparty/cpufeatures
Scanning potential vendored dir: /tmp/opencv/3rdparty/ffmpeg
Scanning potential vendored dir: /tmp/opencv/3rdparty/flatbuffers
Scanning potential vendored dir: /tmp/opencv/3rdparty/include
Scanning potential vendored dir: /tmp/opencv/3rdparty/ippicv
Scanning potential vendored dir: …
```
=> Add support for determineversions API (#612).

pkg/lockfile/apk-installed_test.go, pkg/lockfile/dpkg-status_test.go, pkg/lockfile/helpers_test.go, pkg/lockfile/osv-vuln-result_test.go, pkg/lockfile/parse-cargo-lock_test.go, pkg/lockfile/parse-composer-lock_test.go, pkg/lockfile/parse-conan-lock-v1-revisions_test.go, pkg/lockfile/parse-conan-lock-v1_test.go, pkg/lockfile/parse-conan-lock-v2_test.go, pkg/lockfile/parse-gemfile-lock_test.go, pkg/lockfile/parse-go-lock_test.go, pkg/lockfile/parse-gradle-lock_test.go, pkg/lockfile/parse-maven-lock_test.go, pkg/lockfile/parse-mix-lock_test.go, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-nuget-lock-v1_test.go, pkg/lockfile/parse-pipenv-lock_test.go, pkg/lockfile/parse-pnpm-lock_test.go, pkg/lockfile/parse-poetry-lock_test.go, pkg/lockfile/parse-pubspec-lock_test.go, pkg/lockfile/parse-requirements-txt_test.go, pkg/lockfile/parse-yarn-lock-v1_test.go, pkg/lockfile/parse-yarn-lock-v2_test.go, pkg/lockfile/parse_test.go
Cherry-picked from #553
---
It's required for testing against Windows because it has a different error message, but it's also just a good overall change and landing it separately removes ~25 files from the main PR 😅
=> test: check against error type rather than message

codecov.yml
I'm honestly sure CodeCov isn't bugged (or that somehow we're uploading results from a branch...), but removing this file/ignore increases coverage a little so why not 🤷
=> test: don't ignore anything from coverage

internal/output/sarif.go, internal/sourceanalysis/go.go, internal/url/url.go, internal/url/url_other_test.go, internal/url/url_test.go, internal/url/url_windows_test.go
Turns out that file -> url translation on Windows is busted, and that this is a hard problem that Go has an internal util for that has not yet been made public - I've done what apparently a number of other packages have done which is copying that helper into here and hoping one day it actually becomes public 😢
Note that until #646 is landed, there is no way to actually verify this is fixing the problem - #553 shows the result of both PRs being merged.
=> fix: properly handle file/url paths on Windows

docs/Gemfile, docs/Gemfile.lock
Upgrading `jekyll-feed` broke the ability to preview the docs locally. 
I rolled back the version of `jekyll-feed` and updated the Gemfile.lock. 
[Preview](https://hayleycd.github.io/osv-scanner/)
=> Downgrade jekyll-feed. Update lock file

cmd/osv-scanner/main_test.go
Both vulnerabilities have aliases and this should be reflected in the test output.
=> cmd/osv-scanner: update sarif output in test cases

.golangci.yaml
I did this as a bit of an exercise in how to configure linting a bit more - while not critical, might as well have it and should help with external contributors e.g. it'll flag #658
=> ci: enforce that `cachedregexp` is always used instead of `regexp`

pkg/lockfile/apk-installed.go, pkg/lockfile/dpkg-status.go, pkg/lockfile/parse-gradle-lock.go, pkg/lockfile/parse.go
We're previously agreed that in these situations we should be erroring since the native package manager does not support them but cannot make that change until v2 as it's technical breaking.
In the meantime we've currently got tests that cover these situations but unlike panics we cannot suppress the warnings because of how Go works resulting in a very noisy time when _any_ test fails; it's gotten to the point that I've decided to actually make this PR 😅 
Since in theory these could actually still be useful especially for folks like Scorecard as part of helping confirm the parsers are handling edge-cases, I'm happy to alternatively gate these behind an env variable that is disabled by default but I don't have strong opinions on this.
=> fix: remove noise lockfile warnings

.golangci.yaml
We recently discussed this and agreed that not everything should be a constant - notably this linter seems to have changed in v1.55 so it finds a few more strings it thinks should be constants
=> chore: disable `goconst` linter

pkg/osvscanner/osvscanner.go
This mirrors https://github.com/google/osv.dev/commit/81a02135365a8ff0856588cf844645ed253b5257.
=> Don't include nested vendored libs in determineversions query.

pkg/osvscanner/vulnerability_result.go
this just makes it easier for our users to use.
=> make license allowlist matching case insensitive

.github/workflows/lint-action/action.yml, cmd/osv-scanner/main_test.go, internal/sbom/sbom.go, pkg/depsdev/license.go, pkg/lockfile/extractor.go, scripts/run_lints.sh
Note that the `SBOMReader` refactor wasn't required for this, but my IDE flagged it so I just included it here 🤷
=> refactor: upgrade golangci-lint

cmd/osv-reporter/main.go, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
Fixes #676 
> - Return 0 if there are no findings or errors.
> - Return 1 if there are any findings (license or vulns).
> - Return 128 if no packages are found.
=> Simplify return codes to return 1 if any vulnerability related error

cmd/osv-scanner/fixtures/locks-test-ignore/osv-scanner.toml, cmd/osv-scanner/fixtures/locks-test-ignore/package-lock.json, cmd/osv-scanner/main_test.go, internal/ci/fixtures/vulns/test-vuln-diff-a-a-1.json, internal/ci/fixtures/vulns/test-vuln-diff-a-a.json, internal/ci/fixtures/vulns/test-vuln-diff-a-b.json, internal/ci/fixtures/vulns/test-vuln-diff-b-a.json, internal/ci/fixtures/vulns/test-vuln-diff-b-c.json, internal/ci/fixtures/vulns/test-vuln-diff-c-b.json, internal/testutility/utility.go, pkg/grouper/grouper.go, pkg/grouper/grouper_test.go, pkg/models/results.go, pkg/osvscanner/fixtures/filter/all/configs/b/osv-scanner.toml, pkg/osvscanner/fixtures/filter/all/input.json, pkg/osvscanner/fixtures/filter/all/want.json, pkg/osvscanner/fixtures/filter/none/input.json, pkg/osvscanner/fixtures/filter/none/want.json, pkg/osvscanner/fixtures/filter/some/input.json, pkg/osvscanner/fixtures/filter/some/want.json, pkg/osvscanner/osvscanner.go, pkg/osvscanner/osvscanner_internal_test.go, pkg/osvscanner/vulnerability_result_internal_test.go
Fixes #634 
The actual change is just adding an `Aliases` field to the Group output, that combines all the IDs and aliases together. A lot of fixtures had to be updated though. 
Added an additional test for this in `main_test`, and also modified a test in `osvscanner_internal_tests.go`
Also added `omitempty` tag to `PackageInfo.commit` which it should have contained in the first place.
=> Fix filter ids

.github/workflows/goreleaser.yml, .github/workflows/prerelease-check.yml
Setup a manual release pipeline and convert the old pipeline back to listening on tag pushes. Fixes #632. 
This pipeline allows us to manually run all the pre-release checks before we manually push the tags.
=> Setup manual release pipeline

.goreleaser.yml
Now that there are multiple files under `cmd/osv-scanner/` in addition to `main.go` we need to specify the entire package rather than just the main.go file when releasing.
=> Fix goreleaser build

.pre-commit-hooks.yaml, docs/usage.md
This change exposes a pre-commit hook for people to use that would run osv-scanner when commiting code to their codebase.
Resolves #60.
I manually tested this change by modifying the `.pre-commit-config.yaml` file from the [pipdeptree](https://github.com/tox-dev/pipdeptree) project to the following:
```yml
repos:
- repo: https://github.com/kemzeb/osv-scanner
rev: 321d06b03fbea723004247e6e29aa811861a882f
hooks:
- id: osv-scanner
args: ["-r", "."]
```
...where I ran pre-commit locally by doing the following:
Install the pre-commit script:
```console
pre-commit install 
```
Run while using all the files in the pipdeptree repo, while also providing verbose output produced by osv-scanner (I truncated the output but wanted to make aware that the `-v` option is available):
``` console
pre-commit …
```
=> Add `osv-scanner` pre-commit hook

go.mod, go.sum
Current go mod file does not compile #688 (I am actually unsure how it managed to get merged in the first place, maybe caused by our CI being 1.20 rather than 1.22). 
Latest experimental package requires golang.org/x/tools v0.16.0, which removed a module required by govulncheck.
=> Fix go mod

CHANGELOG.md, docs/usage.md, internal/output/fixtures/test-vuln-results-a.sarif, internal/output/fixtures/test-vuln-results-a_windows.sarif, internal/version/version.go
And fix experimental label in the documentation.
The blog link won't work yet until the blog is released. To test it use the `test.osv.dev` domain.
=> Add changelog for verson 1.5.0

CHANGELOG.md, docs/installation.md
Missed updating the minimum go version change in the changelog, so updating it now.
=> Update changelog to include minimum go version changes

pkg/lockfile/parse-nuget-lock.go, pkg/lockfile/parse-nuget-lock_test.go
If [NuGet central package management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) is enabled, V2 lock files will be generated when restoring projects.
Check out [NuGet source](https://github.com/NuGet/NuGet.Client/blob/a59e64507383b64bcfbe9bf63b34aca946ab0da9/src/NuGet.Core/NuGet.Commands/PackagesLockFileBuilder.cs#L119-L128) for reference.
Since version V2 is backward compatible with V1, the required change to support it is straightforward.
=> Add support for NuGet lock files version 2

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-reusable-pr.yml, .github/workflows/osv-scanner-reusable.yml, docs/github-action.md
=> Create an option to skip/disable upload to code scanning

pkg/osvscanner/osvscanner.go
When --local-db or --offline flags are passed in the user expects no requests containing individual packages to be made to an external service.
=> Return an error if both license scanning and local/offline scanning is enabled simultaneously

go.mod, go.sum
The current version makes osv-scanner unusable against SBOM generated by the latest version of CycloneDx/cdxgen
=> Updating cdxgen-go version in go.mod

internal/semantic/compare_test.go, internal/semantic/parse.go, internal/semantic/parse_test.go, internal/semantic/types.go, internal/utility/vulns/vulnerability.go, pkg/lockfile/ecosystems.go, pkg/models/constants.go
Imports ecosystems from `models`  package rather than `lockfile` for `internal/semantic`.
=> Refactor: attempt to transition into using models.Ecosystems rather than lockfile.Ecosystems

.golangci.yaml, cmd/osv-reporter/main.go, cmd/osv-scanner/main.go, internal/local/check.go, internal/sourceanalysis/go.go, internal/sourceanalysis/rust.go, pkg/config/config.go, pkg/osvscanner/optional_enricher.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go, pkg/reporter/gh-annotations_reporter.go, pkg/reporter/json_reporter.go, pkg/reporter/reporter.go, pkg/reporter/sarif_reporter.go, pkg/reporter/table_reporter.go, pkg/reporter/void_reporter.go
When I originally implemented `Reporter`, IDEs such as GoLand didn't support custom `Printf` functions so I stuck with plain methods and did the `fmt` formatting on the string; that's changed as of GoLand 2023.3 via [GO-5841](https://youtrack.jetbrains.com/issue/GO-5841) 🎉 
Technically adding to `Reporter` is a breaking change but as covered [in this comment](https://github.com/google/osv-scanner/pull/698#issuecomment-1853318857):
> I believe there are no other implementations (at least public on github, from a quick code search) of this interface, and there are no good use cases for implementing this manually instead of using one of the preset implementations we provide.
Either way I think it's better to land these ASAP to reduce the blast radius then to carry them around for possibly a …
=> feat: support `PrintTextf` and `PrintErrorf` on `Reporter`

pkg/reporter/gh-annotations_reporter.go, pkg/reporter/json_reporter.go, pkg/reporter/reporter.go, pkg/reporter/sarif_reporter.go, pkg/reporter/table_reporter.go, pkg/reporter/void_reporter.go
Per https://github.com/google/osv-scanner/pull/706#issuecomment-1870668808
=> fix: remove deprecated `Reporter` methods

cmd/osv-reporter/main.go
Add an option for the github action reporter to not return a failing code when vulnerabilities are found. This can be used to switch the osv-scanner action into a more "informative" mode rather than forcing strictly 0 vulnerabilities. 
The success/failure of a workflow can now indicate whether the workflow itself completely successfully and uploaded scan results, rather than showing the contents of the results. 
A followup PR will be created adding the option to the workflows once this is merged.
=> Add option to not fail on vulnerability being found for github action

cmd/osv-scanner/fixtures/locks-insecure/composer.lock, cmd/osv-scanner/main_test.go, pkg/osvscanner/vulnerability_result.go
Fixes #735 
Also update composer.lock in our integration tests fixture to contain a vulnerability to catch this issue in the future.
=> Show ecosystem and version even if git is shown if the info exists.

cmd/osv-reporter/main.go, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, internal/local/check.go, internal/sourceanalysis/go.go, internal/sourceanalysis/rust.go, pkg/config/config.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go, pkg/reporter/format.go, pkg/reporter/format_test.go, pkg/reporter/gh-annotations_reporter.go, pkg/reporter/gh-annotations_reporter_test.go, pkg/reporter/json_reporter.go, pkg/reporter/json_reporter_test.go, pkg/reporter/reporter.go, pkg/reporter/sarif_reporter.go, pkg/reporter/sarif_reporter_test.go, pkg/reporter/table_reporter.go, pkg/reporter/table_reporter_test.go, pkg/reporter/verbosity.go, pkg/reporter/verbosity_test.go, pkg/reporter/void_reporter.go
Inspired by what was discussed in #698, this PR makes the necessary (breaking) changes to the `reporter` package such that the `Reporter` interface now provides methods for printing at certain levels (i.e. ErrorLevel, WarnLevel, InfoLevel, and VerboseLevel). It also adds a --verbosity option so that users/automated tools can take advantage of this too.
=> Add support for verbosity levels

go.mod, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/osvscanner/osvscanner.go
While the change made in #704 is the ideal solution, it only works for people using go 1.21 or later. Adding a patch version to go.mod will cause go1.20 or earlier to fail to build. Since 1.20 is still fully supported and is still the default version for many workflows, this causes too many breakages for users to be acceptable.
There's a few alternative fixes:  
- Assume latest patch version (This PR)
- This means osv-scanner is no longer checking whether a project is updating to the latest patch version to resolve vulnerabilities, but will still catch users using an out of support go minor version that has no patch available. 
- Remove stdlib vulnerability check entirely / move stdlib vuln check behind a experimental flag
- Add a way to hint to osv-scanner the go version (e.g. …
=> Assume latest patch version if version does not exist

.dockerignore, .goreleaser.yml
Automatically build the github action image as part of the goreleaser pipeline. The image name will be github.com/google/osv-scanner-action , but the image/package will be associated with the osv-scanner repository. 
This might fail if there is a permission issue when building/uploading the image in the release, will explore during release.
=> Build action image when releasing

.github/workflows/goreleaser.yml, .goreleaser.yml, goreleaser-action.dockerfile
Goreleaser only puts the built binaries in the context. (https://goreleaser.com/errors/docker-build/) This causes the custom github action docker build to fail.
This PR adds osv-reporter as something goreleaser builds, and correctly copies in the bash script. Tested to build locally.
I also updated the goreleaser.yml file to exclude the osv-reporter in the output, but I don't know if that will be successful as there's no way to test it.
=> Update goreleaser to fix release pipeline

.goreleaser.yml
#751 didn't completely work (though docker image is successfully published), so this followup PR should hopefully fix the problem.
=> Remove unnecessary docker manifest entry in goreleaser

.github/workflows/goreleaser.yml, .goreleaser.yml
Should be the last goreleaser fix, the previous #752 worked, but revealed another bug. This should fix the binary release error.
=> Final goreleaser fix

pkg/models/results.go, pkg/models/results_test.go
Follow up on https://github.com/google/osv-scanner/pull/655
=> add dependency groups to flattened vulnerability

.goreleaser.yml, goreleaser-action.dockerfile, pkg/osvscanner/osvscanner.go
Add a specific version to github action osv-scanner binary, and also append osv-scanner version to the default user agent.
=> Update github action version

go.mod, internal/resolution/manifest/manifest.go, internal/resolution/manifest/npm.go
Adds `ManifestIO` & npm implementation for parsing manifest files into the `Manifest` struct, and writing patches back out.
Mostly just a copy-paste from what's already been reviewed internally.
=> Guided Remediation: add npm `package.json` manifest parser

cmd/osv-scanner/main.go
"it" is singular but it's following "dependencies" which is plural - also changed "matches" to "checks" as that feels more correct but happy if we want to stick with "matches"
=> fix: improve wording of usage description

go.mod, internal/remediation/relax.go, internal/remediation/relaxer/npm.go, internal/remediation/relaxer/relaxer.go, internal/remediation/remediation.go, internal/resolution/resolve.go
The remediation part of guided remediation :)
Adds the functionality to attempt to fix vulnerabilities in a manifest by relaxing the requirements of its direct dependencies.
I've simplified & refactored `tryRelaxRemediate` (née `RelaxResolve`), so PTAL at that. 
I still need to migrate the part that uses this to make the list of possible 'patches' to the manifest (hence the `//nolint:unused` everywhere), but I didn't want to keep bringing more and more bits into one PR.
=> Guided Remediation: Add dependency relaxation & re-resolution

cmd/osv-scanner/__snapshots__/main_test.snap, internal/output/table.go, internal/remediation/remediation.go, internal/utility/severity/severity.go, internal/utility/severity/severity_test.go
Factored out the CVSS Score parsing from the table output into its own function to reuse it in guided remediation. The new function also returns the human-readable rating string ("LOW", "HIGH", etc.) which I will end up using for the interactive guided remediation mode.
I also made some changes to the table output of the scores:
- Always render the scores to 1 decimal place, so `6.0` instead of just `6`
- Display `0.0` if the CVSS score actually evaluates to 0, vs nothing when there is no severity listed
=> Parse severities for guided remediation

internal/remediation/relax.go, internal/resolution/resolve.go, internal/resolution/resolve_vulns.go
Following on from #765, adds `ComputeRelaxPatches` for generating the possible remediation options after a relock.
Also added a new(ish) cache for OSV API requests, which speeds up the above quite a bit.
=> Guided Remediation: Add computation for all relaxation patches

cmd/osv-reporter/main.go
This is to match the decision made when creating `exit_code_redirect.sh` to not fail if no lockfiles are found.
With the reporter the action will still fail when lockfiles are not found, this just updates it so that it will not fail now.
=> Do not fail if no lockfiles found in github action

internal/resolution/lockfile/lockfile.go, internal/resolution/lockfile/npm.go, internal/resolution/lockfile/npm_v1.go, internal/resolution/lockfile/npm_v2.go, pkg/lockfile/parse-npm-lock.go
Adds the lockfile parsing for in-place updating.
Code is mostly unchanged from what exists internally, mostly just split it up into multiple files.
I've reused and added to the existing (public) npm structs, but this shouldn't impact the scan action.
=> Guided Remediation: Add `package-lock.json` LockfileIO

internal/remediation/in_place.go, internal/remediation/remediation.go, internal/resolution/client/osv_client.go, internal/resolution/dependency_chain.go, internal/resolution/resolve.go, internal/resolution/util/depsdev.go
Adding in-place update computation, for finding 'drop-in' fixes of vulns in indirect dependencies.
I did end up rewriting a lot of this, so I'd appreciate a more thorough review of this PR.
Something to note for the future: unlike what happens internally, the returned patches can be incompatible with each other (i.e. could possibly suggest two different versions for the same package). I'll need to make sure the caller handles this possibility.
=> Guided Remediation: Compute in-place updates

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/main.go
Just the `osv-scanner fix` flag parsing, the command itself doesn't do anything.
I'd appreciate opinions on the naming/aliasing of the flags.
=> Start setting up guided remediation subcommand

internal/resolution/client/npm_registry_client.go, internal/resolution/datasource/depsdev_api.go, pkg/depsdev/license.go
Adds the `osv-scanner/[VERSION]` user agent the grpc requests going to the deps.dev API.
I thought it'd be nice to for deps.dev to be able to see which traffic is coming from license scanning and guided remediation.
CC: @josieang
=> Add user agent to deps.dev requests

internal/remediation/suggester/maven.go, internal/remediation/suggester/maven_test.go, internal/remediation/suggester/suggest.go
This PR adds the implementation for Maven version suggester:
- The latest version of the specified package is returned based on the given options.
- A version range requirement will be replaced to the latest version if this version does not satisfy the constraint.
- Major updates can be ignored with option `NoMajorUpdates` set to true.
=> Automated Updates: add version suggester for Maven

internal/remediation/in_place.go, internal/resolution/dependency_chain.go, internal/resolution/lockfile/npm.go, internal/resolution/lockfile/npm_v1.go, internal/resolution/lockfile/npm_v2.go, internal/resolution/resolve.go
I've used the `dep.Dev` type in the in-place parsed graph to flag dev dependencies.
Ideally, I'd also be able to do the same with the relock graph, it's just that the npm resolver does not resolve any dev dependencies
=> Guided Remediation: Compute Dev dependencies in in-place parsing

.gitignore
I mistakenly added this in #693
=> chore: don't ignore `fixtures` directory

internal/image/image.go
It looks like this function was just renamed so easy to address
=> refactor: replace usage of deprecated function

.goreleaser.yml
Removing redundant versioning for cleaner binary names.
=> Remove version from the binary name.

cmd/osv-scanner/main_test.go, internal/local/check.go, internal/sourceanalysis/rust_test.go, internal/testutility/utility.go
regarding : https://github.com/google/osv-scanner/issues/741
As discussed with google team, moving to using cached local db when not running acceptance tests.
=> Added a switch for using cached local db in test to improve speed

internal/resolution/datasource/maven_registry.go, internal/resolution/datasource/maven_test.go
This PR adds a simple Maven registry API client which sends requests to Maven Central Repository.
For now, this client can only be used to fetch a Maven project. We are able to extend the client to fetch other data (versions, dependencies, etc) in the future.
=> Automated Updates: add a simple Maven registry API client

internal/ci/__snapshots__/vulnerability_result_diff_test.snap, internal/ci/vulnerability_result_diff.go, internal/output/githubannotation.go, internal/output/table.go, internal/sourceanalysis/__snapshots__/go_test.snap, pkg/models/results.go, pkg/osvscanner/__snapshots__/osvscanner_internal_test.snap, pkg/osvscanner/vulnerability_result.go
- Addresses issue #495.
- I'm happy to add tests for the `MaxSeverity` function if this is required for this issue.
=> Maximum severity rating for each Group object in JSON output

cmd/osv-scanner/fix_test.go, cmd/osv-scanner/main_test.go, internal/local/zip_test.go, internal/testutility/utility.go
We've already got this duplicated in two places, and I have need for it in an upcoming PR and @robramsaynz should be using it in #797 so let's move this into `testutility`
=> test: make `createTestDir` a general test utility

.github/workflows/codeql-analysis.yml, .github/workflows/osv-scanner-reusable.yml
I was having a look at the openssf scorecard score as I've not really dug into that before, and saw it was flagging some unpinned actions.
Most of them were about the `osv-scanner` action itself which I don't think can be pinned since the point is to use the latest version for self testing right? but we can pin `actions/download-artifact` and `actions/setup-go` _though_ I'm pretty sure that isn't needed anymore because it was a workaround for https://github.com/github/codeql/issues/13992 and we were just waiting on a new version? either way we'll find out.
=> ci: remove unneeded `setup-go` step and pin `actions/download-artifact`

internal/local/zip_test.go
When doing #832 I leaned `t.Cleanup` is a thing so let's use that instead here
=> test: automatically cleanup test zip server

docs/guided-remediation.md
Counting and grouping of vulnerabilities are different in `fix`. Document this.
[preview link](https://michaelkedar.github.io/osv-scanner/experimental/guided-remediation/#known-issues)
=> Add more guided remediation known issues re: vulnerabilitiy counting

go.mod, internal/sourceanalysis/__snapshots__/integration_test.snap
It was accidentally updated to 1.22.0 with renovatebot 2 weeks ago. We need a way to prevent this from happening.
=> Downgrade go.mod

cmd/osv-scanner/fix_test.go, internal/resolution/manifest/__snapshots__/npm_test.snap, internal/resolution/manifest/fixtures/npm-workspaces/package.json, internal/resolution/manifest/fixtures/npm-workspaces/ws/jquery/package.json, internal/resolution/manifest/fixtures/npm-workspaces/ws/ugh/package.json, internal/resolution/manifest/fixtures/npm-workspaces/z/package.json, internal/resolution/manifest/fixtures/package.json, internal/resolution/manifest/maven_test.go, internal/resolution/manifest/npm.go, internal/resolution/manifest/npm_test.go, internal/testutility/snapshot.go
Slowly adding tests to the guided remediation code.
This adds tests for the npm ManifestIO, and fixed a few things I found when writing them:
- The ordering of the found dependencies was slightly incorrect in some cases.
- `optionalDependencies` weren't being included in relock/relax
- Workspace dependencies were overriding real npm registry dependencies with the same name beyond the scope of the workspace.
Also made a `WithCRLFReplacement()` test snapshot helper for `\r\n` -> `\n` conversion on Windows.
=> GR: Add npm ManifestIO tests & minor fixes

docs/guided-remediation.md
Make it more obvious that only npm is supported with a yellow highlight box.
=> Highlight supported manifests/lockfiles in Guided Remediation docs

pkg/depsdev/license.go
Fixes: #777 
- add MakeVersionRequestsWithContext()
- change old function `MakeVersionRequests` to wrap `MakeVersionRequestsWithContext` with context.Background
=> add MakeVersionRequestsWithContext()

Dockerfile, action.dockerfile
Noticed that renovatebot is updating the docker images past 1.21
=> Pin the dockerfiles to the correct base image

cmd/osv-scanner/__snapshots__/main_test.snap
It looks like we've got some old snapshots that weren't cleaned up by `go-snaps` - this reduces the diff of #866
=> test: regenerate snapshots

internal/image/image_test.go, internal/resolution/manifest/maven_test.go, internal/sourceanalysis/__snapshots__/integration_test.snap, internal/sourceanalysis/integration_test.go, pkg/grouper/grouper_test.go, pkg/models/results_test.go, pkg/reporter/gh-annotations_reporter_test.go, pkg/reporter/json_reporter_test.go, pkg/reporter/sarif_reporter_test.go, pkg/reporter/table_reporter_test.go
None of these need to be within the same package - `internal/suggestor` could also almost be except its calling a single private function, but more notably it highlighted to me that maybe it should be called something like `suggest` anyway because it's main method is `GetSuggestor` resulting in `suggestor, err := suggestor.GetSuggestor`; happy to do a follow-up PR renaming this if folks agree.
=> test: use "public" package where possible

.github/workflows/test-action/action.yml
It seems that v4 is having some teething problems - coverage is no longer being uploaded due to the lack of a token, and it seems like at least some people are getting 500s even when they do provide a token (https://github.com/codecov/codecov-action/issues/1248).
Let's start by downgrading to a known working version, and go from there.
Relates to #784
Before: 
After:
=> ci: downgrade codecov action to v3

internal/image/image_test.go, scripts/run_tests.sh
https://github.com/google/osv-scanner/pull/851#issuecomment-1987566176
@G-Rath this the vibe?
Marked the tests in the file edited in previous PR as and acceptance. 
Flagged the additional image build script added in that PR as only called during acceptance testing too (optional can remove)
=> Follow up PR851 mark acceptance on image tests

.github/workflows/lint-action/action.yml, cmd/osv-scanner/fix/main.go, cmd/osv-scanner/scan/main.go, internal/image/image.go, internal/local/check.go, internal/local/zip.go, internal/output/githubannotation.go, internal/remediation/suggest/suggest.go, internal/resolution/manifest/maven.go, internal/semantic/version-pypi.go, internal/sourceanalysis/go.go, internal/sourceanalysis/rust.go, internal/thirdparty/ar/reader.go, pkg/lockfile/extract.go, pkg/lockfile/extract_test.go, pkg/osvscanner/osvscanner.go, scripts/run_lints.sh
I'm kind of on the fence about this - I actually ran the [`perfsprint` benchmarks locally](https://github.com/catenacyber/perfsprint) and these changes are indeed faster, but they're really in the hotpath; at the same time though we're not importing anything new for this and it could one day catch a use on the hotpath so I'm not sure about disabling it either.
Happy to hear what others think
=> perf: optimize string formatting and update linting

.github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/goreleaser.yml, .github/workflows/link-check-on-push.yml, .github/workflows/link-check.yml, .github/workflows/osv-scanner-reusable-pr.yml, .github/workflows/osv-scanner-reusable.yml, .github/workflows/osv-scanner-unified-action.yml, .github/workflows/prerelease-check.yml, .github/workflows/scorecards.yml
This hardens the workflow permissions so that jobs only have the permissions they need - it's unclear to me from the docs if scorecard currently understands this is the most secure approach (as its docs to me imply it it thinks `permissions: read-all` is best), but that's a scorecard problem.
In doing this, we do harden the permissions of a few jobs that were getting permissions they don't actually need.
=> ci: harden workflow permissions

renovate.json
follow up on https://github.com/google/osv-scanner/pull/833#issue-2160370114
=> fix(renovate): constrain go to 1.21 and do not update golang

docs/offline-mode.md
Otherwise it breaks on front-end, as Jekyll treats `<ECOSYSTEM>` as an HTML tag.
=> [docs] Fix the HTTP link for downloading offline database.

cmd/osv-scanner/__snapshots__/fix_test.snap, cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/__snapshots__/update_test.snap, cmd/osv-scanner/fix_test.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/update_test.go
I was very confused on why _most_ snapshots were all going into `main_test.snap` except for a couple, and it turns out the filename is determined by the call stack (literally `go-snaps` looks for the first frame in a `_test.go` file); I couldn't think of a good way `go-snaps` should enable working around this so instead I decided to refactor our helper a bit.
I think its useful to have all the snaps in their relative files like this vs saving a couple of lines especially given the size and that we're already generating a snapshot for each test.
I've also made a couple of other minor tweaks for consistency while I was at it.
=> test: change how snapshot matchers are called and update example name for consistency

internal/resolution/datasource/maven_test.go, internal/resolution/datasource/npm_registry_test.go, internal/testutility/mock_http.go
Factored out the httptest.Server / handler into one struct for easier reuse in tests.
=> Make MockHTTPServer for tests

cmd/osv-scanner/__snapshots__/fix_test.snap, go.mod, internal/resolution/lockfile/__snapshots__/npm_test.snap, internal/resolution/lockfile/fixtures/npm_registry/@fake-registry-a-1.2.4.json, internal/resolution/lockfile/fixtures/npm_registry/@fake-registry-a-2.3.5.json, internal/resolution/lockfile/npm_test.go, internal/resolution/lockfile/npm_v1.go, internal/resolution/lockfile/npm_v2.go
Added a basic-ish lockfile write test, which needs the mock npm registry.
Also, fixed a bug on an edge-case where if the new version has new dependency types (e.g. newly added `optionalDependencies`) it wouldn't get added to the newly-written lockfile. I had to change how I attempt to preserve formatting to do that.
=> GR: Add simple test for package-lock.json writing

internal/image/testmain_test.go, internal/resolution/datasource/__snapshots__/npmrc_test.snap, internal/resolution/datasource/testmain_test.go, internal/resolution/lockfile/testmain_test.go, internal/resolution/manifest/testmain_test.go
While doing #902 I realised we've got a couple of packages using snapshots but not cleaning them up afterwards - this changes that; I've also opened #903 adding a script to check all packages using snapshots are cleaning them.
=> test: clean and sort snapshots

internal/sourceanalysis/rust.go
Latest rust version (1.77) implemented stripping release binaries by default. This makes the call analysis stop working, so explicitly disable the stripping behaviour when building for analysis.
https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default
=> Fix rust call analysis by explicitly disabling stripping of debug info

internal/resolution/datasource/__snapshots__/npmrc_test.snap, internal/resolution/datasource/npm_registry_cache.go, internal/resolution/datasource/npm_registry_test.go, internal/resolution/datasource/npmrc.go, internal/resolution/datasource/npmrc_test.go, internal/resolution/lockfile/npm_test.go, internal/testutility/mock_http.go
Should fix #899 
Changed the npmrc parsing logic when using `--data-source=native` so that specifying registries with paths (e.g. `//my.registry/package/path:_authToken`) will now correctly add the authorization headers.
Used [npm-registry-fetch](https://github.com/npm/npm-registry-fetch/tree/main) as reference.
=> GR: Parse paths in npmrc auth fields correctly

internal/image/__snapshots__/image_test.snap
This is sort of a rebase of #902 but I decided to do a new PR because #898 updated `go-snaps` and #904 sorted (literally) `npmrc_test.snap` so the only thing left is to remove the old snapshots which is just in `image_test.snap`
Closes #902
=> test: clean up image snapshots

pkg/lockfile/helpers_test.go
Ran into this while working on other stuff - currently if two packages are the same except for their groups, the failure message doesn't indicate that which is confusing
=> test: include groups when describing package details

.github/workflows/checks.yml, .github/workflows/prerelease-check.yml, .github/workflows/test-action/action.yml
This will hopefully resolve the issues we're having with the v3 action, but requires the `CODECOV_TOKEN` secret to be configured per [this document](https://docs.codecov.com/docs/adding-the-codecov-token) which needs to be done by someone with repository permissions to set secrets.
=> ci: upgrade Codecov to v4

pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-npm-lock.go, pkg/lockfile/parse-nuget-lock.go, pkg/lockfile/parse-pipenv-lock.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse.go
This replaces some of our custom code for map-based operations with almost-standard-library versions
=> refactor: use `maps` functions instead of custom implementations

.github/workflows/test-action/action.yml
I'm pretty sure that inputs are case-insensitive, but to be on the safe side let's update this to match anyway
=> ci: ensure input name case matches just to be safe

internal/remediation/remediation.go, internal/remediation/remediation_test.go
Check the vuln's aliases when using the `--vulns` or `--ignore-vulns` flag.
Closes #922
=>  GR: Support filtering on alias IDs

.github/workflows/checks.yml
This saves a bit of processing power, and also can help Codecov by reducing some of the API calls it makes which impact rate limiting
=> ci: cancel in-progress runs when new changes are pushed

scripts/generators/GenerateMavenVersions.java, scripts/generators/generate-debian-versions.py, scripts/generators/generate-packagist-versions.php, scripts/generators/generate-pypi-versions.py, scripts/generators/generate-rubygems-versions.rb
This updates the generators used to build fixtures for `semantic` in a few different ways particularly if you're running them locally:
- you can use `VERSION_GENERATOR_PRINT` to control if successes, failures, or everything is outputted
- if any comparisons fail, then the generator will exit with code 1
- the generated fixture file will now assuredly have a final newline, in accordance with our editor config
---
this is the first of a couple of updates to the generators based on what I've already done in `osv-detector`
=> chore: improve version fixture generators for local usage

internal/output/__snapshots__/sarif_test.snap, internal/output/result.go, internal/output/sarif.go
This stabilizes the order in the SARIF output so that it is deterministic, as #937 proved it was not.
=> fix: ensure the sarif output has a stable order

cmd/osv-scanner/__snapshots__/update_test.snap
Jackson core released a new version that automated updates is now updating to, updating the fixtures to keep the tests passing.
=> Fix snapshot for test

internal/output/githubannotation.go, internal/output/result.go, internal/output/table.go
This "improves" our coverage artificially since the unhappy path is not coverable and this reduces us from three uncoverable lines to one.
I think this is worth doing as it feels more representative especially since we're panicking meaning we consider this a very unlikely and "on fire" situation, so we're hiding that within a particular function whose name makes that clear a la `regexp.MustCompile`
=> refactor: encapsulate getting the working directory in a helper function

scripts/generators/GenerateMavenVersions.java, scripts/generators/generate-cran-versions.R, scripts/generators/generate-debian-versions.py, scripts/generators/generate-packagist-versions.php, scripts/generators/generate-pypi-versions.py
Cherry-picked from https://github.com/G-Rath/osv-detector/pull/241
---
Currently the generators assume that all packages in an OSV are for their respective ecosystem which since they download ecosystem-specific databases is _mostly_ true, but there are a few OSVs that are for packages that exist across more than one ecosystem.
This has not been a problem up until now because either the versions in such OSVs happen to be compatible with native ecosystem version parser or we're skipping invalid versions for legacy reasons, but now GHSA-5844-q3fc-56rh exists which has versions that are invalid in Ruby.
=> chore: only extract versions from packages in the generator ecosystem

.github/workflows/lint-action/action.yml
Cherry-picked from #897
---
We can drop the `skip-pkg-cache` option now as caching has been removed in favor of `actions/setup-go`s caching
=> ci: upgrade `golangci/golangci-lint-action` to v5

cmd/osv-scanner/__snapshots__/main_test.snap, internal/sourceanalysis/__snapshots__/integration_test.snap, pkg/osvscanner/__snapshots__/osvscanner_internal_test.snap, pkg/osvscanner/fixtures/filter/some/input.json, pkg/osvscanner/fixtures/filter/some/want.json, pkg/osvscanner/osvscanner.go, pkg/osvscanner/osvscanner_internal_test.go
osv.dev integrates Debian security tracker data into existing CVE entries, filtering out unimportant vulnerabilities.
=> Disable all unimportant vulnerabilities

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/locks-many/alpine.cdx.xml, cmd/osv-scanner/fixtures/sbom-insecure/alpine.cdx.xml
This updates busybox to 1.36.1-r27 to resolve all current vulnerabilities, and then updates the snapshots to match.
This is a bit odd as 1.36.1-r27 doesn't actually exist on the distro this SBOM is created for (alpine 3.17) , where the highest version is 1.35.0-r30. However, as 3.17 is now out of support, no more fixes are being backported for 1.35.0. 
The *ideal(?)* behavior would not show the 3.19/3.20 vulnerabilities on 1.36.1 when scanning Alpine 3.17, but because of distro in purls still being undefined, all alpine advisories are returned. When this is eventually implemented, we should revert this PR.
=> Fix snapshots and alpine version

internal/resolution/manifest/fixtures/parent/grandparent/pom.xml, internal/resolution/manifest/fixtures/parent/pom.xml, internal/resolution/manifest/maven.go
Previously, the path is always relative to the provided path to `pom.xml`, however, this path should be relative to the current parent path.
Also we observe that sometimes `pom.xml` is omitted in `</relativePath>` so when this happens, we manually append `pom.xml` to file path.
=> make Maven parent path relative on current project

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/sbom-insecure/alpine.cdx.xml
The version of zlib (in the purl) seems to be randomly selected for testing purposes (1.2.10-r2), as it doesn't match the rest of the SBOM. The problem is that a particular version never existed, and only showed up because it was incorrectly enumerated in osv.dev. 
Now that the version enumeration has been fixed it causes different results to show up in the testing snapshot. 
This PR makes all the version numbers for zlib in the SBOM consistent, and sets it to `1.2.10-r0` which actually exists. (And the snapshot will not change when the fixed alpine enumeration moves to production.)
=> Select a version that actually exists

.github/workflows/test-action/action.yml
This keeps failing on macOS, so let's skip it for now
=> ci: don't try to upload code coverage on macOS

cmd/osv-scanner/fix/model.go, internal/tui/in-place-info.go, internal/tui/vuln-list.go
lipgloss v0.11.0 made it so that all the `Style` methods no longer mutate the style, which I was relying on.
=> Fix broken TUI styling

internal/resolution/manifest/maven.go
There are two places that we call `mergeParents()`:
- Merging data from parent pom.xml files
- Importing dependency management from another project
In `mergeParents()`, we first check if `relativePath` is defined to know if we can parse parent locally.
However, this only applies for the first case but not for importing dependency management.
Also, once we start fetching parent pom.xml from upstream, we should no longer parse locally. 
This PR adds `allowLocal` to `mergeParents()` to specify if we allow parsing local parent pom.xml, and once a parent is fetched from upstream, `allowLocal` is set to false.
=> Dependency imports should always be fetched from upstream

Dockerfile, action.dockerfile
The base docker images are pinned to go 1.21. With 8fd553a, this breaks the GitHub reusable workflows. This PR pins the images to [the official 1.21.11 one](https://hub.docker.com/layers/library/golang/1.21.11-alpine3.19/images/sha256-6c5f76c897971f1b6ff0e447941440889016b18805812660a83b5275e862298d?context=explore). This should fix the issue.
=> Update base docker image for golang 1.21.11

internal/manifest/fixtures/maven/parent/pom.xml, internal/manifest/fixtures/maven/with-parent.xml, internal/manifest/fixtures/universe/basic-universe.yaml, internal/manifest/maven.go, internal/manifest/maven_test.go
https://github.com/google/osv-scanner/issues/531
This PR merges parent pom.xml by paring locally or fetching from upstream (Maven Central for now).
When merging a parent pom.xml, only `pom` packaging is allowed. Once we fetch a parent from upstream, parsing from local is no longer allowed.
The project is also interpolated to get rid of properties, and dependencies are also processed (dedup and import).
=> Merge parent projects for Maven pom.xml

CONTRIBUTING.md, cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/locks-many/alpine.cdx.xml, cmd/osv-scanner/fixtures/sbom-insecure/alpine.cdx.xml
Remove busybox from alpine SBOM to get a more consistent unit test.
=> Remove busybox from alpine SBOM

docs/configuration.md, docs/license-scanning.md
Add documentation for the newly added config package override feature #814
=> Add documentation for the configuration.

CHANGELOG.md, cmd/osv-scanner/__snapshots__/main_test.snap, internal/output/__snapshots__/sarif_test.snap, internal/version/version.go
=> v1.8.0 Changelog

.golangci.yaml, internal/customgitignore/walk_up_to_root.go, internal/image/extractor.go, internal/output/identifiers.go, internal/output/table.go, internal/sbom/cyclonedx.go, internal/thirdparty/ar/reader.go, pkg/osv/osv.go, pkg/osvscanner/osvscanner.go
This enables the [`indent-error-flow`](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow) rule from `revive`, which flags redundant `else` statements.
---
It turns out that by configuring `revive`, we actually inadvertently disabled all of its rules, and there are a few we're failing on that I think are worth re-enabling - this is one of them
=> refactor: enable `revive/indent-error-flow`

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/main_test.go, internal/utility/vulns/vulnerability.go
This changes how we compare ecosystems so that the suffix is only considered when it is present for _both_ ecosystems being compared, since we can't reliably extract that.
Resolves #769
=> fix: only care about ecosystem suffix if present in both ecosystems when determining equality

internal/sourceanalysis/__snapshots__/integration_test.snap, internal/sourceanalysis/integration_test.go
Using a different Go version changes where the affected line is in the stdlib, so let's just set it to -1 to make it easier for local development with newer go versions
=> Update tests to support go version changes

scripts/generators/GenerateMavenVersions.java, scripts/generators/generate-cran-versions.R, scripts/generators/generate-debian-versions.py, scripts/generators/generate-packagist-versions.php, scripts/generators/generate-pypi-versions.py, scripts/generators/generate-rubygems-versions.rb
This has always been allowed by the spec but now there's at least one real-world advisory in the Debian database like this which causes it to error.
=> fix: ensure that `package` exists in `affected` property

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/osvscanner/osvscanner.go
https://github.com/google/osv-scanner/pull/968 only filters out unimportant vulnerabilities from `pkgVulns.Vulnerabilities` but not from `pkgVulns.Groups`. This causes some unimportant vulnerabilities to still appear in the scanner output. 
Fixing this issue by ignoring all unimportant vulnerability groups.
=> filter out unimportant vulnerabilities from vuln group

.github/workflows/semantic.yml
Cherry-pick of https://github.com/G-Rath/osv-detector/pull/182
---
This setups up a dedicated workflow for running the `semantic` test suite using the latest generated fixtures:
- every sunday
- whenever a generator or the workflow is changed
- via a `workflow_dispatch`
This helps ensure high confidence in `semantic` across ecosystems; the workflow also exports the generated files as an artifact which makes it easy to update the committed version of each fixture without requiring the native ecosystem components (i.e. Ruby, Java, R, etc) to be installed.
Note currently this is using v3 of the artifact actions - I'll upgrade to v4 in a follow-up PR, since it will require further work due to them switching to using immutable artifacts.
At some point I'm also keen to explore this for the API …
=> ci: setup workflow to run `semantic` tests weekly

pkg/osv/osv.go
The existing code tried to do what `errgroup` does, limit concurrency and return the first error if present, but had a deadlock scenario.
Fixes #1077
=> fix: use errgroup to avoid hydration deadlock scenario

internal/output/markdowntable.go, internal/output/table.go
This lets us drop some conditionals - weirdly it doesn't seem to work if we move the conditional `text.DisableColors` call into `reporter.New` even though that does work for the vertical reporter...
=> refactor: just disable color output rather than tracking terminal width

internal/remediation/suggest/maven.go, internal/remediation/suggest/maven_test.go, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go
The current design of Maven manifest reading has some problems:
- requirements that are not useful for resolution are also included
- requirement origins mess the dependency resolution as well
To address the issues above, in this PR:
- requirements returned are only those ones needed for dependency resolution
- passing Maven dependencies with origins so we can look up their original requirement
- passing requirements that are needed for updates only individually
However there are still known issues for this implementation:
- profiles are not yet fully supported (pending deps.dev changes)
- original requirements may not be found for dependencies with placeholders in their names
=> Refactoring `manifest.Read()` for Maven

.github/workflows/osv-scanner-unified-action.yml, docs/github-action.md
Fixes #1090 
Also makes our osv-scanner action in this repo track the main branch so we always dogfood the latest version.
=> Update github action docs in osv-scanner

goreleaser-action.dockerfile
This allows the OSV-scanner GitHub action to automatically run go call analysis. This does increase the total size of the image (no compression, no layer caching) by 5x. From 70mb to 400mb  , as it now includes the go compiler in the image.
=> Add go compiler to enable call analysis in the github action

internal/output/table.go
I mistakenly changed the order that styles are applied in #1087 for the table formatter so our custom styles were immediately overridden when the rounded style was applied
=> fix: restore custom styling to table format

pkg/lockfile/fixtures/npm/same-package-different-groups.v1.json, pkg/lockfile/fixtures/npm/same-package-different-groups.v2.json, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-npm-lock.go, pkg/lockfile/parse-nuget-lock.go
This resolves an inconsistency in the scanner output for npm packages that appear in the same tree multiple times but in different groups; this happens because the table outputter deduplicates on groups on the assumption that a package can only appear in a single group which is incorrect for the NPM ecosystem.
To address this, I've introduced an internal map type that ensures groups are merged when a package is added, with the twist that if either instance of a package being merged is in no groups then that is the result of the merge because implicitly that means an instance of the package is in the "production" group which takes priority over the other groups.
This is something that should most likely be improved on the future, but right now this fix should be good enough to ship since …
=> fix: ensure that npm dependencies retain their "production" grouping

cmd/osv-scanner/scan/main.go, docs/usage.md
Not deprecating this yet, as there are still a few questions to work out before making the new container scanning flag public. 
Mainly: 
- Add support for OCI images?
- Replace current docker flag?
=> Add warning to the default docker container scanning method

pkg/lockfile/parse-npm-lock.go
Fix bug in the npm grouping code, the current maps.Copy method doesn't use the merging applied in details.add, causing inconsistent test failures.
=> Fix npm grouping

.github/workflows/lint-action/action.yml, .golangci.yaml, internal/local/zip.go, internal/output/result.go, internal/semantic/version-maven.go, scripts/run_lints.sh
There's nothing too major here though we do get to remove a bunch of config for deprecated linters that have finally been removed; the more exciting thing is when we move to Go v1.22 as there's a few linters that'll start running like for cleaning up our looping variables
=> refactor: update linter and address minor violations

internal/resolution/manifest/__snapshots__/maven_test.snap, internal/resolution/manifest/maven.go
Currently, the newly added dependency management is not written correctly - `dependency` tags are missing.
This PR fixes this by specifying `dependency` in the struct.
=> Fix the wrong dependencies/dependency tags

docs/supported_languages_and_lockfiles.md
Update the documentation that the current Maven resolver does not handle test dependencies.
=> Update docs: test dependencies not in the resolved graph

internal/utility/vulns/vulnerability.go, internal/utility/vulns/vulnerability_test.go
=> fix: ensure that `semantic` is passed a valid `models.Ecosystem`

internal/remediation/suggest/maven.go, internal/remediation/suggest/maven_test.go, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go
Previously, `origRequire` is not set in patches from suggest, however we plan to use this field to differentiate patches from override, this PR sets `origRequire` for patches from suggest so that `manifest.Write()` is able to only add dependencies from patches generated by override.
=> Set the original requirement in patches from suggest

.github/workflows/staleness.yml
Such issues will never not be stale right up until work on v2 starts (and even then they'll likely be stale on and off)
(note I'm not entirely sure if this will work re the spaces - I've found some issues on the action repo that suggest it should, but no actual example docs; I think we just need to try it and see 🤷)
=> ci: don't mark v2 wishlished issues as stale

.github/workflows/staleness.yml
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label
> Anyone with triage access to a repository can apply and dismiss labels.
=> Exempt backlog label from stale treatment

internal/remediation/suggest/maven.go, internal/remediation/suggest/maven_test.go, internal/resolution/manifest/maven.go
Copying the `EcosystemSpecific` data from the `Manifest` to the `ManifestPatch` is a bit cumbersome for the override strategy, and `ManifestPatch` already has a field for the original manifest.
I don't think the current Maven `EcosystemSpecific` data is ever going to differ from the what's in the original manifest?
=> Add original manifest to Maven ManifestPatch

internal/manifest/fixtures/maven/transitive.xml, internal/manifest/fixtures/universe/basic-universe.yaml, internal/manifest/maven.go, internal/manifest/maven_test.go
Currently, Maven dependency management is not added to the override client so they are not considered when computing Maven dependency graph. 
This PR adds all direct dependency management to override client so that transitive dependencies are resolved correctly.
=> Add Maven dependency management to override client

.github/workflows/staleness.yml
Run hourly and increase operations per run
This will allow a single pass through all the existing issues to complete, and react to removing the stale label with less latency
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-github_token-in-github-actions
=> Increase frequency of staleness runs

cmd/osv-reporter/main.go, cmd/osv-scanner/__snapshots__/main_test.snap
If all vulnerabilities are not called, don't return an non zero exit code in osv-reporter.
=> fix(osv-github-action): If all vulnerabilities are not called, don't return an non zero exit code in osv-reporter

go.mod, go.sum
Pre-release is failing due to a vulnerability on dependency `github.com/docker/docker` and this PR updates it to the latest version.
=> chore: update dependency `github.com/docker/docker`

internal/manifest/maven.go, internal/resolution/manifest/__snapshots__/maven_test.snap, internal/resolution/manifest/fixtures/maven/my-app/pom.xml, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go
This PR fixes two issues when reading/writing Maven manifest:
- when merging parents, if `groupId` or `version` is empty, inherit these values from the parent;
- only trim elements with no inner elements, otherwise inner elements will be wiped.
=> fix: only trim XML elements with no inner elements

.github/workflows/staleness.yml
Is there a way to catch errors like this, pre-merge?
=> fix(workflow): correct permission name

.github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/goreleaser.yml, .github/workflows/osv-scanner-unified-action.yml
- `branches` is invalid for `on.merge-group`
- `inputs.commit` was not being defined (and `refs` defaults to using the relevant tag, based on https://github.com/google/osv-scanner/actions/runs/10278144006/job/28441323524#step:2:106)
=> ci(workflow): address address github.com/rhysd/actionlint findings

cmd/osv-scanner/fix/main.go, internal/resolution/lockfile/lockfile.go, internal/resolution/lockfile/npm.go, internal/resolution/manifest/manifest.go, internal/resolution/manifest/maven.go, internal/resolution/manifest/npm.go
Add a check for the ecosystem & error for unimplemented native registry clients.
=> fix(guided remediation): error on `--data-source=native` for Maven

.github/workflows/lint-action/action.yml, cmd/osv-scanner/fix/noninteractive.go, internal/image/extractor.go, internal/image/scan.go, internal/output/vertical.go, pkg/osvscanner/osvscanner.go, pkg/reporter/cyclonedx_test.go, pkg/reporter/gh-annotations_reporter_test.go, pkg/reporter/json_reporter_test.go, pkg/reporter/sarif_reporter_test.go, pkg/reporter/table_reporter_test.go, pkg/reporter/vertical_reporter_test.go, scripts/run_lints.sh
`golangci-lint` just released [v1.60.1](https://github.com/golangci/golangci-lint/releases/tag/v1.60.1) recently.
This PR updates the version of `golangci-lint` to its latest version. This should unblock the `golangci-lint` failures.
=> chore: use the latest version of `golangci-lint`

internal/manifest/maven.go, internal/resolution/manifest/fixtures/maven/parent/pom.xml, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go
https://github.com/google/osv-scanner/issues/1169
Currently, Maven updater only supports writing updates in base pom.xml, but we would like to write updates to local parent pom.xml to minimize diffs.
This PR supports writing updates to parent pom.xml:
- when building patches, local parent pom.xml files are walked through to collect original dependencies and properties (this step may be done when we merge parents in reading manifest). Paths to parent manifests are recorded in the origin so we don't need to walk through the parents again.
- when writing the patches, if any patch is found for specific parent path, the manifest will be overwritten with the new patches.
TODO: we should investigate how to test the updated local parent pom.xml which is not in this PR.
=> feat: write Maven updates to parent pom.xml if possible

.github/workflows/checks.yml, .github/workflows/pr-check.yml
Enforces PR naming to follow with the Git [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- Uses https://github.com/amannn/action-semantic-pull-request to check
- Fails to comply will result in the PR title check failing:
=> chore: add PR title check to follow Git commit convention

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/fix/main_test.go, docs/guided-remediation.md, internal/remediation/in_place.go, internal/remediation/in_place_test.go, internal/remediation/override.go, internal/remediation/override_test.go, internal/remediation/relax.go, internal/remediation/relax/npm.go, internal/remediation/relax/npm_test.go, internal/remediation/relax/relax.go, internal/remediation/relax_test.go, internal/remediation/remediation.go, internal/remediation/upgrade/config.go, internal/remediation/upgrade/config_test.go, internal/remediation/upgrade/level.go, internal/remediation/upgrade/level_test.go, scripts/examples/auto_guided_remediation.py, scripts/generate_mock_resolution_universe/main.go
closes #1177
- Adds `--upgrade-config` flag for configuring allowed upgrades on a per-package basis.
- Hide & deprecate previous `--disallow-major-upgrades` and `--disallow-package-upgrades` flags.
- Update docs & example script to use new flag.
=> feat(guided remediation): add `--upgrade-config` flag

internal/resolution/manifest/__snapshots__/maven_test.snap, internal/resolution/manifest/fixtures/maven/my-app/pom.xml, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go
https://github.com/google/osv-scanner/issues/1184
When encoding tokens to pom.xml, tabs are escaped and this is not what we want.
In this PR, before writing to pom.xml, we replace all escaped tabs with unescaped characters.
=> fix: unescape tabs before writing to pom.xml

internal/remediation/fixtures/zeppelin-server/parent/osv-scanner.toml
Missed this in #1202, probably because its in a parent's `dependencyManagement`
=> chore: add missed test ignore vuln

cmd/osv-scanner/__snapshots__/fix_test.snap, cmd/osv-scanner/fix/noninteractive.go, docs/guided-remediation.md
Closes #1203
Add a `FIXED-VULN-IDS: ` line to non-interactive guided remediation output, which is a comma-separated list of the IDs of the vulnerability resolved, in alphabetical order.
=> feat(guided remediation): Add `FIXED-VULN-IDS` to non-interactive output

cmd/osv-scanner/__snapshots__/update_test.snap
Package `com.fasterxml.jackson.core:jackson-core` has a new version `2.18.0-rc1` https://central.sonatype.com/artifact/com.fasterxml.jackson.core/jackson-core/2.18.0-rc1
This PR updates the snapshot of `update` subcommand to this latest version.
=> chore: update test snapshots

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-composite-config.toml, cmd/osv-scanner/main_test.go, docs/configuration.md, pkg/config/config.go, pkg/config/config_internal_test.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go
This rewrites the package overrides logic to be composition based, granting a lot more flexibility:
```
[[PackageOverrides]]
ignore = true
[[PackageOverrides]]
group = "dev"
ignore = true
[[PackageOverrides]]
ecosystem = "go"
ignore = true
[[PackageOverrides]]
name = "axios"
ignore = true
[[PackageOverrides]]
name = "axios"
ecosystem = "npm"
group = "dev"
ignore = true
```
While some of these might seem a bit extreme, ultimately I think this is probably the way to go as the logic itself is very straightforward and it gives a lot more power to the people.
Since `config` is a public package, I've had to deprecated the related existing public methods and there's a bit of naming & structural yuck but I figure that's not a big deal since v2 is right around the corner and again the logic itself …
=> feat: support composite-based package overrides

pkg/lockfile/apk-installed.go, pkg/lockfile/apk-installed_test.go
The latest release of osv.dev enforces the Alpine release version suffix in queries.
Make the apk-installed parser use the latest Alpine version (`v3.20`) when it can't find the version file to stop it from erroring.
=> fix: make Alpine ecosystem fallback to latest release version

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/fix/model.go, cmd/osv-scanner/fix/noninteractive.go, cmd/osv-scanner/fix/state-relock-result.go, internal/remediation/__snapshots__/testhelpers_test.snap, internal/remediation/override.go, internal/remediation/override_test.go, internal/remediation/relax.go, internal/remediation/relax_test.go, internal/remediation/remediation.go, internal/remediation/testhelpers_test.go, internal/resolution/resolve.go, internal/resolution/resolve_test.go, scripts/generate_mock_resolution_universe/main.go
Adds functionality to allow guided remediation to fix vulns in `dependencyManagement` dependencies that do not appear in the resolved dependency graph of the POM - useful for 'remediating' POMs without any actual dependencies.
I've accomplished this by checking if each of the original management dependencies (*excluding* those inherited from parents) appear in the graph after the initial resolution. If they're missing, I add them to the graph as direct dependencies (not resolving their transitive dependencies).
This behaviour is disabled by default, and I've added a `--maven-fix-management` flag to enable it. I was going to try combine this and `--ignore-dev` into a `--groups` flag but it seemed like it would be a bit too complicated.
=> feat(guided remediation): remediate unresolved dependency management vulns

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-complex-licenses-config.toml, cmd/osv-scanner/main_test.go, docs/configuration.md, pkg/config/config.go, pkg/config/config_internal_test.go, pkg/osvscanner/vulnerability_result.go
This allows you to configure the scanner to completely ignore the license of a package in a way that is explicit, as oppose to configuring `license.overrides` to set the package license to an allowed one.
Resolves #1124
=> feat: allow explicitly ignoring the license of a package in config

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-composite-config.toml, cmd/osv-scanner/fixtures/osv-scanner-reasonless-ignores-config.toml, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
Currently if you don't provide a reason for an override the scanner will just output "because: " which looks weird and results in a trailing space in our snapshots which IDEs try to trim.
Since we want to encourage people to provide a reason, I've changed the scanner to explicitly state "(no reason provided)" in this situation
=> fix: don't assume there's always a reason for a package being filtered out

internal/resolution/lockfile/npm_test.go, internal/resolution/manifest/maven_test.go, internal/sbom/cyclonedx_test.go, internal/sbom/spdx_test.go, pkg/grouper/grouper_test.go, pkg/models/results_test.go, pkg/osvscanner/osvscanner_internal_test.go
The examples in the docs suggest passing `want, got` rather the other way around which we're already mostly doing but have a few cases where we're not - likewise with the messaging we've been mostly consistent between three slightly different phrasing, which I've updated to always be `(-want +got)` which is what's in the example for `cmp.Diff`
=> test: ensure `cmp.Diff` usage is consistent

pkg/config/config.go
`toml.DecodeFile` does literally what we're doing except without the custom error messages, which I don't think should matter as we don't intentionally expose those as an actual API; there also doesn't seem to be anything special about what `UseOverride` is doing to prevent it from using `tryLoadConfig`.
This will mean error output will probably have changed slightly, but it should still be accurate and we're not purposely providing custom or dedicated errors in this package so I don't think it should be considered breaking.
=> refactor: simplify and reuse `tryLoadConfig`

pkg/lockfile/apk-installed.go, pkg/lockfile/dpkg-status.go, pkg/lockfile/osv-vuln-results.go, pkg/lockfile/parse-cargo-lock.go, pkg/lockfile/parse-composer-lock.go, pkg/lockfile/parse-conan-lock.go, pkg/lockfile/parse-gemfile-lock.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-gradle-lock.go, pkg/lockfile/parse-gradle-verification-metadata.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-mix-lock.go, pkg/lockfile/parse-npm-lock.go, pkg/lockfile/parse-nuget-lock.go, pkg/lockfile/parse-pdm-lock.go, pkg/lockfile/parse-pipenv-lock.go, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-poetry-lock.go, pkg/lockfile/parse-pubspec-lock.go, pkg/lockfile/parse-renv-lock.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-yarn-lock.go
I think it's time to start getting the word out...
Resolves #1021
=> chore: deprecate parser functions in favor of their extract equivalents

.github/workflows/staleness.yml
I noticed that this hasn't been pinned, which it should be to make scorecard happier
=> ci: pin `actions/stale` to a commit

.github/workflows/pr-check.yml
I noticed that this hasn't been pinned, which it should be to make scorecard happier
=> ci: pin `amannn/action-semantic-pull-request` to a commit

.golangci.yaml, cmd/osv-scanner/scan/main.go, internal/image/extractor.go, internal/image/image.go, internal/image/layer.go, internal/local/zip_test.go, pkg/config/config.go, pkg/lockfile/osv-vuln-results.go, pkg/osvscanner/osvscanner.go, pkg/reporter/void_reporter.go
Followup to #1259 
Resolves #1257
=> refactor: Follow revive rules across the repo

pkg/config/config.go
This is a pseudo bug I introduced way back in #190 - it doesn't actually happen as our implementation always explicitly sets the property after we've successfully parsed the file into the struct, but it is possible for refactors like #1248 to reveal this and ultimately we don't want this behaviour so we might as well fix it.
=> fix: don't allow `LoadPath` to be set via config file

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-unknown-config.toml, cmd/osv-scanner/main_test.go, pkg/config/config.go, pkg/config/config_internal_test.go, pkg/config/fixtures/unknown-key-1.toml, pkg/config/fixtures/unknown-key-2.toml, pkg/config/fixtures/unknown-key-3.toml, pkg/config/fixtures/unknown-key-4.toml, pkg/config/fixtures/unknown-key-5.toml, pkg/config/fixtures/unknown-key-6.toml, pkg/config/fixtures/unknown-key-7.toml
Currently the scanner does not check if there were unrecognized properties when loading configuration files, meaning that typos can easily slip through; to help avoid this, I've modified `tryLoadConfig` to return an error if there are any undecoded keys in the metadata.
While this could cause existing configs to start erroring, I don't think this should be considered a breaking change as such configurations would inherently causing different behaviour than what was desired and thus be a downstream bug themselves.
This will also mean that old versions of the scanner going forward would not be compatible with configs for even newer versions of the scanner that introduce new config properties, which is could be a little annoying but I don't think outweighs the benefit of this validation …
=> feat: error if configuration file has unknown properties

cmd/osv-scanner/__snapshots__/main_test.snap, internal/identifiers/identifiers.go, internal/identifiers/identifiers_test.go, internal/output/result.go, internal/output/sarif.go, internal/output/table.go, pkg/grouper/grouper.go, pkg/grouper/grouper_models.go
For container scanning, we should only display DSA results and hide their related CVEs.
- Add DSA's related CVEs to the same group.
- Sort the group IDs with the DSA first. (DSA is more important than CVE, and one DSA contains multiple CVEs)
- Don't print CVE records when there is a DSA (this reduces noise in container scanning results).
=> feat: group DSA and its CVEs together

pkg/config/config_internal_test.go
This behaviour changed as a result of both #1252 (which makes `LoadPath` no longer a recognized config key) and #1249 (which causes the scanner to error when a config has an unknown key), but they didn't directly conflict with each other so got landed on `main` without this being picked up
(fwiw I'm not worried about this being a reoccurring thing that's worth guarding or preventing somehow as its usually pretty rare 🤷)
=> test: update case to reflect recent config parsing changes

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/main_test.go, internal/local/check.go
This reduces the amount of noise generated when using `--offline` if a database is not available for a particular ecosystem. While it was suggested that we could have some form of general error cache, for now I've just optimized for this specific case as really it's the one we expect the most and (in part) I think the nature of Go makes the more generic improvement a bit too faffy vs the gain.
Resolves #1005
=> fix(offline): report all ecosystems without local databases in one single line

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/sbom-insecure/bad-purls.cdx.xml, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
While I believe such situations indicate a bug in the tool used to generate the SBOM, outputting the PURLs should make it easier to debug the issue.
Resolves #86
=> fix: output invalid PURLs when scanning sboms

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/go-project/nested/go-version-config.toml, cmd/osv-scanner/fixtures/go-project/nested/go.mod, cmd/osv-scanner/fixtures/go-project/nested/osv-scanner.toml, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
Currently we assume that there'll only ever be one occurence of `stdlib` when overriding the Go version but really there can be an occurrence _per `go.mod`_ file
Resolves #1273
=> fix: apply go version override to _all_ instances of the `stdlib`

pkg/osv/osv.go
The current `maxConcurrentRequests` setting is insufficient for container scanning, where one scan may report more than a thousand vulnerabilities. Bump it up to 1000 to fix it.
=> fix: bump osv max concurrent requests

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-composite-config.toml, cmd/osv-scanner/main_test.go, docs/configuration.md, pkg/config/config.go, pkg/config/config_internal_test.go, pkg/osvscanner/vulnerability_result.go
This implements the ability to ignore vulnerabilities in a matching group of packages while still reporting license violations, as the inverse to `license.ignore`.
Resolves #1226
=> feat: support `vulnerabilities.ignore` in package overrides

pkg/osvscanner/osvscanner.go
By capturing `stderr` and outputting it as an error when `docker` exits with a non-zero code, it should make it easier to catch and debug issues such as unsupported images, images that do not exist, or cannot be accessed due to lack of authentication.
Currently this just assumes the output from Docker will be helpful enough since we're not able to rely on a particular structure that'd let us parse and understand the actual error, but it should still be a lot better then the current behaviour of saying the docker image was scanned with no packages being found (which we do still do as changing that would be more complex).
Because we've not got any tests for this, here's some manual testing:
```
osv-scanner on  improve/docker-error-output [$?] via 🐹 v1.22.7 via  v20.11.0 took 4s
❯ …
```
=> fix: improve handling if `docker` exits with a non-zero code when trying to scan images

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/osvscanner/osvscanner.go
This both ensures the output is consistent for tests and I think is better for readability as it means packages end up grouped by their ecosystem
=> fix: sort sbom packages by PURL

cmd/osv-scanner/__snapshots__/fix_test.snap
There is a [vulnerability](https://osv.dev/vulnerability/GHSA-78wr-2p64-hpwj) reported on `commons-io:commons-io` and guided remediation further bumps the version to its fixed version.
=> test: update snapshots for guided remediation 

exit_code_redirect.sh, internal/customgitignore/dir_test.go, internal/customgitignore/walk_up_to_root.go, internal/sourceanalysis/go.go, pkg/lockfile/parse-conan-lock.go, pkg/osv/osv.go, pkg/osvscanner/vulnerability_result.go
I found these while working on other stuff
=> fix: address a number of typos

cmd/osv-scanner/fix/main.go, docs/guided-remediation.md, docs/offline-mode.md, internal/resolution/client/osv_offline_client.go
#1295
Support the `--experimental-offline` and `--experimental-download-offline-databases` flags in `osv-scanner fix`.
This is pretty inefficient since `local.MakeRequest()` reads and parses the zip file every time it's called. I didn't want to make too many changes to make it more efficient since we'll probably end up refactoring it in v2.
Also fixed the links to headings on the offline docs page.
=> feat(guided remediation): support offline database in fix subcommand

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/sbom-insecure/with-duplicates.cdx.xml, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
While from what I understand duplicates should not be possible in a valid SBOM, apparently they happen and it's useful for us to report + skip them.
Since doing this efficiently requires use of a map we in turn have to sort the packages to ensure a consistent output order, leading to me discovering that we're not already sorting the packages - I've opened #1288 to land that change first.
Resolves #330
=> fix: warn about and ignore duplicate entries in SBOMs

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fix/main.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/main.go, docs/guided-remediation.md, docs/offline-mode.md, docs/supported_languages_and_lockfiles.md, pkg/osvscanner/osvscanner.go
Closes #1339 and closes #1121 
Adds flags to use offline mode for vulnerabilities (`--experimental-offline-vulnerabilities`) and transitive resolution separately (`--experimental-no-resolve`)
The original `--experimental-offline` flag retains the same behaviour by functionally setting both of these flags.
=> feat: add `--experimental-offline-vulnerabilities` and `--experimental-no-resolve` flags

.prettierignore, internal/image/pathtree/pathtree_test.go, internal/lockfilescalibr/language/javascript/nodemodules/extractor.go
Ideally, node package extracts can be done with packagejson extractor directly (As every dir inside a node_modules directory has a package.json file), but that changes the image scanning snapshots too much to be part of this initial PR, and introduces new OS findings that are difficult to filter out. 
This keeps the existing solution of extracting directly with node_modules by implementing an extractor that wraps the `packagejsonlock` extractor to minimise snapshot changes.
=> feat: migrate node-modules to a osv-scalibr extractor

internal/semantic/parse.go
Having ecosystems sorted by their name makes it easier to review this section of code
=> refactor(semantic): sort ecosystems by name

internal/semantic/fixtures/alpine-versions.txt, internal/semantic/version-alpine.go
While I'm pretty these are technically invalid, they're easy to support and without this Alpine is the only comparator that panics when parsing an empty string which I think is a little sad.
=> fix(semantic): support parsing versions without a numeric component

internal/semantic/version-semver-like.go
While I'm a little reluctant to do this as I'm sure I included these for a reason, they're apparently not covered by any tests and with `semantic` expected to go public soon, I think it's a bit nicer to have them gone until someone can prove they're needed as some of these could arguably be a breaking change to remove.
I'm pretty sure the bulk of this was present as part of having `semantic` rebuild the parsed version for debugging when I was writing the implementation, but that's not actually a feature so we don't explicitly need to be doing it - this won't stop us from reintroducing the logic in future if we decide we want it
=> refactor(semantic): remove unneeded logic in parsing semver-like versions

internal/semantic/version-rubygems.go
I realised that I have overly complicated the act of returning the result of comparing components in this function, and that the last two conditions will never be true as we loop over the largest number of components 😅
=> refactor(semantic): simplify comparing of RubyGem version components

internal/semantic/version-pypi.go
Currently this return is not covered because we're explicitly doing all three possible comparisons, so we might as well move the equality check to the end as the default
=> refactor(semantic): remove unneeded condition in PyPI version comparator

internal/semantic/version-pypi.go
These letters naturally compare in the right order, so we can just compare them directly which saves us a loop and an untestable `panic`.
(this will conflict with #1362)
=> refactor(semantic): simplify comparing of "pre" letters in PyPI versions

internal/semantic/parse_test.go
Notably this adds coverage over the Ubuntu entry, since that reuses Debian so we don't have any explicit tests for that in the comparison tests.
We also no longer need to be manually adding `CRAN` since `lockfile` supports it
=> test(semantic): include ecosystems not supported by `lockfile`

internal/remediation/suggest/maven_test.go, internal/resolution/manifest/maven_test.go, internal/utility/maven/maven_test.go, internal/utility/vulns/vulnerability_test.go, pkg/lockfile/parse-pdm-lock_test.go, pkg/models/vulnerability_test.go, pkg/reporter/cyclonedx_test.go, pkg/reporter/gh-annotations_reporter_test.go, pkg/reporter/json_reporter_test.go, pkg/reporter/sarif_reporter_test.go, pkg/reporter/table_reporter_test.go, pkg/reporter/vertical_reporter_test.go
Typically with table tests the inner variable is called `tt`, which we're doing in most places already but not everywhere - and as a result, this lead to linting picking up a few `copyloopvar` violations that were previously ignored due to the different variable name
=> test: use traditional `tt` variable name and remove unneeded loop-copy-var

cmd/osv-scanner/__snapshots__/main_test.snap, internal/output/__snapshots__/machinejson_test.snap, internal/sourceanalysis/__snapshots__/go_test.snap, pkg/models/results.go, pkg/osvscanner/__snapshots__/osvscanner_internal_test.snap, pkg/osvscanner/osvscanner.go, pkg/osvscanner/osvscanner_internal_test.go, pkg/osvscanner/vulnerability_result.go
Resolves https://github.com/google/osv-scanner/issues/1378
=> feat(container-scanning): set unimportant vulns as uncalled

pkg/osvscanner/vulnerability_result.go
#1329 removed the slices import in `vulnerability_result.go`, because it was no longer using it.
At the same time, #1385 added a new usage of the module.
Add the import back to make osv-scanner build again.
=> fix: add "slices" import back in

docs/output.md
Corrected JSON field names in the osv-scanner documentation. Previously, one key was incorrectly called `sourcePackage` and was changed to `source`.
Closes https://github.com/google/osv-scanner/issues/1391
=> docs: corrected field names in osv scanner results in the JSON doc

pkg/models/__snapshots__/vulnerabilities_test.snap, pkg/models/__snapshots__/vulnerability_test.snap, pkg/models/testmain_test.go, pkg/models/vulnerabilities_test.go, pkg/models/vulnerability_test.go
This should make it easier to maintain since we won't need to edit raw JSON - I wouldn't say this is strictly better as some of the tests were small enough that I'd argue the initial overhead of using snapshots makes it less of a win, but ultimately these don't change often so I think it's still better to be consistent with the rest of the codebase
(I've also got a fix or two coming up in this section which'll be made easier by this)
=> test: rewrite `models` to use snapshots and tables

internal/customgitignore/dir_test.go
This isn't major, but it means we're more consistent across the codebase in how we're doing tmp directories in tests
=> test: use internal utility for creating tmp directory

internal/output/__snapshots__/output_result_test.snap, internal/output/html.go, internal/output/output_result.go, internal/output/output_result_test.go, internal/utility/severity/severity.go
Refactored the [HTMLResult](https://github.com/google/osv-scanner/blob/9ea8aa57b45890a288a138b600900679ba6c98d1/internal/output/html.go#L19) into a unified structure that can be reused by other output formats. This new structure presents results hierarchically, grouping vulnerabilities by ecosystem, source, and package. Compare to the original vulnerabilityResult, it contains more information, such as vulnerability count (called/uncalled/fixable/unfixable/severity), package/vulnerability fix information, etc.
Follow-up PRs:
- Merge this into the v2 branch (via https://github.com/google/osv-scanner/pull/1396)
- Leverage this structure to generate a table package-view output.
- Update html.go and HTML templates to use the OutputResult.
=> feat(output): add a unified output result

internal/resolution/lockfile/fixtures/npm_type_order/package-lock.json, internal/resolution/lockfile/npm.go, internal/resolution/lockfile/npm_test.go, internal/resolution/lockfile/npm_v1.go, internal/resolution/lockfile/npm_v2.go
Changes two things for package-lock.json parsing:
1. Made it so packages installed in unknown locations (e.g. under a non-existent package) are ignored (following npm's behaviour), instead of triggering a panic.
2. Made missing dependencies in the lockfile *not* cause an error. npm would typically raise an error here, *unless* the missing dependency under a workspace's dependency graph. I think it's ok if we're more lenient than npm here.
=> fix(guided remediation): handle extraneous/missing packages in package-lock.json more leniently

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/osv-scanner-duplicate-config.toml, cmd/osv-scanner/main_test.go, internal/config/config.go, internal/config/config_internal_test.go, pkg/osvscanner/osvscanner.go
Currently if you have multiple ignores for a vulnerability, we just silently use the first one; this has us instead print a warning to make it more obvious when that occurs.
I've not had it error as it doesn't feel like a big enough deal to be worth erroring, though maybe that would be better as I can't think of an actual reason to have duplicate entries 🤔 
Resolves #1367
=> feat: warn if a vulnerability is ignored multiple times in the same config

cmd/osv-scanner/__snapshots__/main_test.snap, internal/output/__snapshots__/output_result_test.snap, internal/output/output_result.go, internal/output/table.go
Fixes #1315
For container scanning, instead of listing hundreds of vulnerabilities, the output now shows the affected packages.
**Changes:**
- Added a summary listing the number of affected packages and vulnerabilities, including severity counts and the number of fixable vulnerabilities.
- Grouped results by ecosystem and source.
- Added a prompt message to inform users about the HTML and vertical output options.
**Future Plans (to be implemented after the comprehensive layer and base image information are available):**
- Add a layer info summary.
- Add base image information.
**Sample output:**
=> feat(output): show package view for container scanning table result

.github/workflows/semantic.yml, .gitignore, internal/semantic/compare_test.go, scripts/generators/generate-redhat-versions.py
This adds a `semantic` fixture generator for the Red Hat ecosystem - as this ends up being just under 2mb, I've not committed the file like the others, instead making the test suite only use it if it's actually present.
It works by leveraging [`rpm`s built-in Lua interpreter](https://rpm-software-management.github.io/rpm/manual/lua.html), which includes exposing the `vercmp` function meaning we can have `rpm` tell us what the result of comparing two versions are so long as there's a version of that available.
In terms of actually getting a version of `rpm`, that turns out to be a lot harder with Docker I assume just because CentOS & co is a less open-source-y distro vs the others; there are images, but they're all generally very big. In an interesting twist though it turns out Debian …
=> ci: add versions fixture generator for Red Hat

internal/image/scan.go
The current v2 container scanning doesn't report any Debian-related vulnerabilities. The reason is that the extractor takes the package name and package version to match against OSV records. But OSV records store records with the source name. Debian packages may have a different source name than their package name (also source version). For example: 
The new change will convert the given package information to its corresponding source information for matching, if the source information is specified.
=> fix: replace Debian package name with its source name

cmd/osv-scanner/scan/main.go
When `serve` is enabled, set the `format` to html (regardless of the `output` flag).
=> fix: set format to HTML when requesting serving resutls

.github/workflows/lint-action/action.yml, .golangci.yaml, cmd/osv-scanner/fix/model.go, pkg/models/results.go, scripts/run_lints.sh
This PR updates `golangci-lint` to v1.62.2, and removes `gomnd` from the list of disabled linters since it is deprecated.
=> chore: update golangci-lint to version 1.62.2

.github/workflows/lint-action/action.yml, cmd/osv-scanner/main_test.go
This test makes a lot of unnecessary not found requests on `repository.apache.org`. This PR removes the test until we fix it.
=> test(maven): remove the test of transitive scanning on native data source

pkg/osv/osv.go
Resolves https://github.com/google/osv-scanner/issues/1411#event-15601233836
This change parallelizes BatchQuery sending with the maximum concurrent number set at 10.
Performance improvement: Using `rocket.chat.json` as an example (3 BatchQuery sending), it reduces the scanning time from 26 seconds to 17 seconds.
=> feat(performance): parallelize batch query sending

.github/workflows/renovate-validator.yml, renovate.json
This PR defines a new workflow to validate renovate config.
=> ci: add a workflow to validate renovate config

internal/resolution/client/client.go
In every `DependencyClient` we have, `MatchingVersions()` is just a call to `Versions()` plus semver matching, which is computationally expensive. It also was being called on every edge of the pre-fetched graphs.
Removed it to reduce CPU usage and hopefully improve performance with Maven resolution / Guided Remediation.
I've also skipped fetching things with `MavenDependencyOrigin` set (e.g. dependencyManagement dependencies) since there's potentially hundreds of them.
=> fix: remove redundant calls from `PreFetch`

.github/workflows/lint-action/action.yml
Recently `golangci-lint` timeouts quite often, as suggested, increase the timeout to 5m.
=> chore: increase timeout for `golangci-lint`

internal/scalibrextract/filesystem/vendored/vendored.go, internal/scalibrextract/filesystem/vendored/vendored_test.go, pkg/osvscanner/internal/scanners/walker.go
Finish a TODO and use the vendored extractor. This also fixes an issue with the extractor using os.Open instead of the fsys open.
=> feat: Add and fix vendored extractor

cmd/osv-scanner/__snapshots__/main_test.snap
Because of the new API changes on osv.dev, we are matching more vulnerabilities! Updated the snapshots to the new results
=> chore: Update snapshots

scripts/generators/generate-alpine-versions.py, scripts/generators/generate-debian-versions.py, scripts/generators/generate-pypi-versions.py, scripts/generators/generate-redhat-versions.py, scripts/report_uncleaned_snapshots.py
Apparently I've not been as consistent on this as I thought I was, so as punishment I've gone through all the scripts and made sure they're using single quotes by default - aside from still being used within `f` strings due to how that syntax works for string literals within interopolations, I have retained the usage of double quotes in four `print` calls which have single quotes in them to avoid doing an escape
=> chore: use single quotes by default in Python scripts

cmd/osv-scanner/__snapshots__/main_test.snap, internal/clients/clientimpl/localmatcher/localmatcher.go, internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/clients/clientinterfaces/vulnerabilitymatcher.go, internal/imodels/ecosystem/ecosystem.go, internal/imodels/imodels.go, pkg/osvscanner/osvscanner.go
Sets up logging to only return one error log per database that fails to load, and also adds a LoadEcosystem function to preload/preerror databases
imodels.go part can be safely ignored as that is removed in a followup PR.
=> feat: Update local matcher to the new requirements for resolve

internal/clients/clientimpl/localmatcher/localmatcher.go, internal/clients/clientimpl/localmatcher/zip.go, internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/config/config.go, internal/config/config_internal_test.go, internal/imodels/ecosystem/ecosystem.go, internal/imodels/imodels.go, internal/scalibrextract/ecosystemmock/extractor.go, pkg/osv/osv.go, pkg/osvscanner/filter.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/scan.go, pkg/osvscanner/vulnerability_result.go, pkg/osvscanner/vulnerability_result_internal_test.go
This PR refactors PackageInfo to be accessed via methods, which will perform necessary transformations on the underlying inventory as needed.
This also adds the ecosystemmock extractor which allows you set the return value of the Ecosystem() function.
TODO: Add tests for imodels. I will add tests in a followup PR once we are confident we are sticking with this approach and it works with the other refactors.
=> refactor: imodels PackageInfo refactor to use functions

experimental/javareach/README.md, experimental/javareach/cmd/reachable/main.go, experimental/javareach/go.mod, experimental/javareach/javaclass.go
This adds the beginnings of a Java reachability analyser that recursively parses class constant pools (https://docs.oracle.com/javase/specs/jvms/se22/html/jvms-4.html#jvms-4.7) for references to other classes. 
The intention is to see if this can be used to exclude transitive dependencies
from vulnerability scanning completely, if they can be proven to be
unreachable.
There's still a lot of TODOs remaining (recorded in the Go source as comments). This tool currently expects
all dependency class files to be available (passed via `--classpath`).
=> feat: Experimental code to start java class reachability.

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/fix/noninteractive.go, docs/guided-remediation.md
Adds a `--no-introduce` flag to `osv-scanner fix --non-interactive` to remove patches from consideration if they introduce new vulnerabilities.
(I haven't actually tested this because I'm struggling to find a project that would introduce vulns...)
=> feat(guided remediation): Add flag to exclude patches that would introduce new vulns

internal/utility/maven/maven.go, internal/utility/maven/maven_test.go
To align with how we scan in OSV-Scalibr, change `ParentPOMPath` to be based on relative path.
Also only call this function for local scans - we don't need to know parent path for upstream pom.xml.
=> refactor: use relative path to get Maven parent path

docs/installation.md, renovate.json
This should unblock #1472 failing to run go mod tidy.
=> fix: renovatebot update golang version in config

internal/remediation/in_place.go, internal/resolution/dependency_chain.go
`devDependencies` can be declared in a workspace, which is not a direct dependency (`root` -> `workspace` -> `dev`). Made the IsDev check that `in-place` uses also check these so that `--ignore-dev` works properly for `in-place` with npm workspace.
(`--ignore-dev` still doesn't behave correctly for `relax` with workspaces, but relax doesn't really work with workspaces anyway)
Also fixed a potential panic with in-place & private registries that don't behave as expected w.r.t. `optionalDependencies` being in regular `dependencies`
=> fix(guided remediation): npm workspaces devDeps in in-place strategy

Dockerfile, action.dockerfile
https://github.com/google/osv-scanner-action/issues/54
This PR updates the base docker image in Dockerfile to be `golang:1.23.5-alpine3.21`.
=> fix: update base docker image in Dockerfile

pkg/osvscanner/filter.go, pkg/osvscanner/osvscanner.go
Linux source packages are likely to be kernel packages, which generally do not apply in a container context,
=> fix: Ignore linux source packages

cmd/osv-scanner/__snapshots__/main_test.snap, internal/clients/clientimpl/baseimagematcher/baseimagematcher.go
Thanks to Josie and Eve, we can now do ChainID scanning on empty layers directly.
=> feat: Chainid on empty

docs/output.md, docs/scan-image.md, docs/supported_languages_and_lockfiles.md, internal/clients/clientimpl/baseimagematcher/baseimagematcher.go, internal/output/html/report_template.gohtml
Several small changes:
- Update the output doc to include HTML output
- Update Feedback link to point to the correct feedback discussion
- Clarify the error logging message to warn people to update osv-scanner if base image scanning fails.
- Actually fail base image scanning to avoid spamming people with the log.
=> docs: Update output and add HTML output as an option in the output.md doc.

README.md, docs/installation.md, docs/scan-image.md
And fix an incorrect flag.
We can safely use @latest because v2 module only has prereleases at the moment, so latest will pick the latest prerelease.
=> docs: Update docs to point to latest

docs/_sass/color_schemes/_variables.scss, docs/_sass/color_schemes/custom_dark.scss, docs/_sass/custom/custom.scss, docs/_sass/highlight/native.scss, docs/supported_languages_and_lockfiles.md, docs/usage.md
- Update font to be more readable, Overpass is much harder to read for dense text, and bold text fades into the background. Use more standard text font of Source Sans Pro (3)
- Fix code blocks being very hard to read
- Fix Tables to not have gaps
New version of docs: https://another-rex.github.io/osv-scanner/supported-languages-and-lockfiles/
Old version of docs: https://google.github.io/osv-scanner/supported-languages-and-lockfiles/
=> docs: Polish up documentation CSS and font

cmd/osv-scanner/internal/helper/helper.go
changes are in file osv-scanner/cmd/osv-scanner/internal/helper/helper.go
1.Added a global variable servePort with a default value of "8000"
2.Added a new CLI flag --port that allows users to customize the port number used when serving the HTML report
3.Removed the hardcoded port number from the ServeHTML function, using the global servePort variable instead
4. The flag's Action function updates the global servePort variable when a custom port is specified
These changes allow users to specify a custom port using the --port flag when using the --serve option, while maintaining the default port 8000 if no custom port is specified.
=> feat: Allow setting of the port number when using the --serve flag by adding a new --port (String) flag

cmd/osv-scanner/__snapshots__/main_test.snap, internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/imodels/imodels.go, internal/utility/vulns/vulnerabilities.go, internal/utility/vulns/vulnerabilities_test.go, internal/utility/vulns/vulnerability.go
This fixes offline scanning having different results compared to using the API. Seems to have two causes:
- vulnerabilities.Include function tests whether a vulnerability is included in aliases as well, and offline scanning skips those vulns if it is included in aliases. However, this is not the behavior of online scanning, where we return all records that match and do not skip alised vulns.
- osv.dev query code has a special section to edit stdlib versions without a patch version to always assume it's at the max patch version. This code is not replicated in offline matcher code.
- I initially placed it in the query code because I didn't want to show the patched version in the output. But I think it's probably a good thing that we show how we are interpreting a version rather than …
=> fix: offline scanning having different results than online

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/locks-insecure/bun.lock, go.mod, go.sum, pkg/osvscanner/internal/scanners/extractorbuilder.go, pkg/osvscanner/internal/scanners/lockfile.go
Also reorder all the extractors so it's easier to read
We actually had a duplicate extractor defined in there.
This also fixes the issue with SBOM extraction discussed here: https://github.com/google/osv-scanner/discussions/1529#discussioncomment-12017733 
Though we still need to follow up with documentation updates.
=> feat: Update scalibr and add support for bun.lock

.github/workflows/osv-scanner-reusable-pr.yml, .github/workflows/osv-scanner-reusable.yml, .github/workflows/osv-scanner-unified-action.yml, .github/workflows/prerelease-check.yml, actions/scanner/action.yml, cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/image/main.go, cmd/osv-scanner/scan/source/main.go, docs/github-action.md, docs/scan-source.md, internal/scalibrextract/vcs/gitrepo/extractor.go, internal/scalibrextract/vcs/gitrepo/extractor_test.go, pkg/osvscanner/internal/scanners/extractorbuilder.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/scan.go
Also removes the `--json` flag since that has been deprecated for a while now. The json tests are not deleted, as there are the same tests with the `--format json` flag.
Succeeds: #1311 
Closes: #1277
=> feat: Make skip git the default behavior

cmd/osv-scanner/__snapshots__/main_test.snap
I feel like ideally this shouldn't actually be in the Java test, but potentially eliminating it is out of my wheelhouse :)
=> test: update image scanning snapshots

cmd/osv-scanner/fix/noninteractive.go, internal/output/output_result.go
I'm not sure if this ever actually matters, but I assume we want to always be using this function whenever we "sort OSVs by their IDs" for consistency
=> fix: use the same sorting logic everywhere for sorting OSVs by their IDs

.golangci.yaml
While it's not been a massive issue or anything, it's pretty easy to enforce and means one less thing for us maintainers to remember when reviewing
=> ci: ensure that `testutility.Skip` is used over `t.Skip` and friends

cmd/osv-scanner/main_test.go
Currently, because we're not using `snaps.Skip` the Windows and MacOS test suites report obsolete snapshots that should be cleaned up
=> test: use skip instead of a condition so that `go-snaps` knows snapshots are not obsolete

docs/scan-source.md
Update documentation to specify that the SBOM file must follow the file name convention. Addresses https://github.com/google/osv-scanner/discussions/1529#discussioncomment-12017733
=> docs: Update SBOM extraction documentation

cmd/osv-scanner/internal/helper/callanalysis_parser.go, cmd/osv-scanner/internal/helper/helper.go, experimental/javareach/javaclass.go, internal/clients/clientimpl/baseimagematcher/baseimagematcher.go, internal/config/config.go, internal/customgitignore/walk_up_to_root.go, internal/datasource/npmrc.go, internal/osvdev/osvdev.go, internal/output/html.go, internal/output/markdowntable.go, internal/output/output_result.go, internal/resolution/manifest/npm.go, internal/scalibrextract/ecosystemmock/extractor.go, internal/testutility/utility.go, internal/tui/dependency-graph.go, internal/tui/tui.go, internal/utility/maven/maven.go, internal/utility/results/results.go, pkg/models/results.go, pkg/osvscanner/osvscanner.go
This addresses most of the violations reported by Golang - the remaining ones are most todo comments.
Not all of these are perfect, but I think most of them are a slight improvement; there are a few that also made me think the "thing" in question might want revisiting, such as `IsAcceptenceTest` which should probably actually be named something like `IsAcceptenceTesting`.
=> refactor: rewrite comments to be prefixed with the subject name

internal/output/html/base_image_template.gohtml, internal/output/html/package_table_template.gohtml, internal/output/html/script.js
converts NodeList to Array before using `.some()`
=> fix(html): fix HTML filter

cmd/osv-scanner/main_test.go, internal/testutility/utility.go
I think there are even better names we could use for both of these helpers, but given we're not using them that much for now I've just fixed the most immediate issue with the current name
=> refactor: rename test helper for clarity

.github/workflows/lint-action/action.yml, .golangci.yaml, cmd/osv-scanner/__snapshots__/main_test.snap, internal/sourceanalysis/__snapshots__/integration_test.snap, scripts/run_lints.sh
At least this time it's a different snapshot 🤷 
Patch https://github.com/google/osv-scanner/pull/1623 so that workflows all pass
=> test: update snapshots and upgrade golangci-lint

internal/spdx/verify_test.go
We're testing a public method, so the tests can live in a dedicated package
=> test(spdx): use dedicated test package

pkg/lockfile/helpers_test.go, pkg/lockfile/node-modules_test.go
This test was landed around the same time that the utility was landed, and I forgot to go back and clean it up
=> test: deduplicate `createTestDir` helper

cmd/osv-scanner/scan/source/main.go
This doesn't need to be public so we might as well make it private like all our other command `action` functions
=> refactor(cmd): make function private

cmd/osv-scanner/__snapshots__/fix_test.snap, cmd/osv-scanner/fix/fixtures/override-maven/pom.xml
My IDE found these while I was working on some bigger test stuff - I assume they're not load bearing for the actual tests, so this'll mean less noise in diffs
=> test: remove trailing whitespace and add end-of-file newline

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/locks-many/osv-scanner.toml, cmd/osv-scanner/fixtures/osv-scanner-call-analysis-config.toml, cmd/osv-scanner/fixtures/osv-scanner-duplicate-config.toml, cmd/osv-scanner/main_test.go, internal/sourceanalysis/__snapshots__/integration_test.snap, internal/sourceanalysis/integration_test.go
In addition to accounting for the new `musl` vulnerability (CVE-2025-26519), this also updates our Go call analysis tests to be stable on both Go 1.23 and 1.24, since the former is what we're using locally while the latter is what CI is using
=> test: update snapshots and fixtures

.golangci.yaml, internal/testutility/utility.go
The only violation we have of this currently is expected due to a limitation of `t.TempDir`
Cherry-picked from #1622
=> chore: enable `usetesting` linter

internal/testutility/utility.go
This is a neat little trick I thought of while cleaning up the snapshots - all its saving us from is having to stick `TEST_ACCEPTANCE=true` in front of our `go test` calls, but I think it's nice to have the test suite not require that when you're running a specific acceptance test.
Credit to `go-snaps` for proving it must be possible, since this is what it does to determine if a snapshot is obsolete or that the tests have just not been run.
I've gone with the slightly awkward name `isThisTestRunTarget` as I felt it was less ambiguous than `isThisTestRunning` and similar, since yes the test must be running if the function is being called... 😅
=> test: don't skip acceptance tests when targeted with `-run`

cmd/osv-scanner/fix/model.go, cmd/osv-scanner/fix/noninteractive.go, cmd/osv-scanner/update/main.go, internal/remediation/in_place_test.go, internal/remediation/suggest/maven.go, internal/remediation/testhelpers_test.go, internal/resolution/client/client.go, internal/resolution/client/npm_registry_client.go, internal/resolution/dependency_subgraph.go, internal/resolution/depfile/depfile.go, internal/resolution/lockfile/lockfile.go, internal/resolution/lockfile/npm.go, internal/resolution/lockfile/npm_test.go, internal/resolution/lockfile/npm_v1.go, internal/resolution/lockfile/npm_v2.go, internal/resolution/manifest/manifest.go, internal/resolution/manifest/maven.go, internal/resolution/manifest/maven_test.go, internal/resolution/manifest/npm.go, internal/resolution/manifest/npm_test.go, scripts/generate_mock_resolution_universe/main.go
To unblock removing `pkg/lockfile` for the full v2 release.
Just copied the necessary parts into the internal directories. Guided remediation is being moved into OSV-Scalibr, so I'll do a proper refactor as part of that move.
There's still one usage left with [`VKToPackageDetails`](https://github.com/google/osv-scanner/blob/3bd1565fd31266b9899747840b8223ab6b7ed225/internal/resolution/util/depsdev.go#L15), which is needed in calls to [`vulns.IsAffected()`](https://github.com/google/osv-scanner/blob/3bd1565fd31266b9899747840b8223ab6b7ed225/internal/utility/vulns/vulnerability.go#L144).
=> fix: remove usage of `pkg/lockfile` from guided remediation

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/fix/main_test.go
Both flags have been deprecated for some time, V2 is a good opportunity to remove them.
=> chore: remove deprecated flags of `fix` subcommand

cmd/osv-scanner/__snapshots__/fix_test.snap, cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/__snapshots__/update_test.snap, cmd/osv-scanner/fix/main_test.go, cmd/osv-scanner/fix_test.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/update_test.go, internal/datasource/maven_registry_test.go, internal/datasource/npmrc_test.go, internal/osvdev/osvdev_internal_test.go, internal/remediation/suggest/maven_test.go, internal/resolution/manifest/maven_test.go, pkg/osv/osv_test.go
This makes a lot of our tests align with the function under test, so that tooling can more accurately link tests with their subjects.
The main change is that the format for tests on private methods should be `Test_<method name>` whereas we've been doing `Test<public name version of method name>`
=> test: update names to match their subjects

internal/remediation/override.go, internal/remediation/suggest/maven.go, internal/remediation/suggest/maven_test.go, internal/utility/maven/maven.go, internal/utility/maven/maven_test.go
This PR applies the Maven version comparison workarounds in the updater. To make the function reusable, moves the version comparison to `internal/utility/maven`.
Also considering that all version strings are parsed to semver first for comparison, this PR pre-parse the versions and store them in a map.
=> feat(updater): use version comparison workarounds in Maven updater

experimental/javareach/cmd/reachable/main.go, experimental/javareach/jar.go, experimental/javareach/reachable.go, experimental/javareach/uniqueq.go
- Support detection of dependency injection for some popular frameworks.
- Add support for handling dynamic code loading by assuming that all class files in the package using dynamic code loading are reachable.
- Remove old cmdline invocation on extracted .class files. Only support .jar for now for simplicity.
- Remove explicit recursion and add `UniqueQueue` data structure to simplify the enumeration algorithm.
- Refactor more code into `javareach` package.
=> feat(javareach): Various improvements.

internal/output/html/script.js, internal/output/html/style.css
Added a spinner indicating iframe is loading. Fixes #1524 
https://github.com/user-attachments/assets/b690e802-33ed-4f10-9f1e-389e132b1df0
=> feat: add a loading animation to the osv iframe

experimental/javareach/cmd/reachable/main.go, experimental/javareach/jar.go, experimental/javareach/reachable.go
- Support loading of dependencies from nested JAR files (e.g. BOOT-INF for Spring Boot applications)
- Add flag to enable profiler for debugging performance issues.
=> feat(javareach): Supported nested JARs.

experimental/javareach/cmd/reachable/main.go, experimental/javareach/jar.go, experimental/javareach/reachable.go
- Better handle Spring Boot applications by mapping classes in BOOT-INF/classes to the root application, so that we can apply our `AssumeAllClassesReachable` strategy for dealing with dependency injection.
- Handle service providers in META-INF/services/ 
- Handle META-INF/versions/ directories when building our class -> artifact map.
- Fix some bugs in our class finding by properly handling inner classes and generics. 
- Add a log line printing out some final metrics on reachability.
=> feat(javareach): Various improvements

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/source/main.go, docs/offline-mode.md
This PR moves offline flags out of experimental mode and removes the deprecated `experimental-call-analysis` flag
=> feat: move offline flags out of experimental mode

cmd/osv-scanner/internal/helper/helper.go
https://github.com/google/osv-scanner/pull/1664 missed one experimental flag
=> fix: correct local-db-path name

cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/scan/image/main.go, cmd/osv-scanner/scan/source/main.go
https://github.com/google/osv-scanner/pull/1519 added a global variable for shared flags has caused issues when using generic flags. For tests running concurrently, the shared "allowlist" variable is sometimes overwritten, leading to flaky license tests. 
Thanks @michaelkedar for pointing out!
=> fix: don't use global variable for flags

cmd/osv-scanner/fix/main.go, cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/source/main.go, docs/supported_languages_and_lockfiles.md, docs/usage.md
This PR moves a few transitive scanning flags from experimental and aligns with `fix`:
- `experimental-no-resolve` -> `no-resolve`
- `experimental-resolution-data-source` -> `data-source`
- `experimental-maven-registry` -> `maven-registry`
=> feat: move transitive scanning flags from experimental

internal/testutility/utility.go
This improves on #1630 so that now attempting to run a specific child test should result in it always running regardless of if its an acceptance test or not, e.g.
```
go test ./cmd/osv-scanner/ -run 'Test_run_OCIImage/Invalid_path'
```
Technically, this implementation will only work when the helper is used at the parent level even though the helper itself should work in the parent or child test functions, but all of our current usages are at the parent level and I couldn't think of any advantage to moving this to the child so I've not bothered supporting the inverse even though it should be trivial to do.
=> test: only check parent test name when deciding if an acceptance testis being targeted with `-run`

cmd/osv-scanner/testmain_test.go
Currently we got a lot of noise from `osv-scalibr` libraries which makes it hard to see what actually failed - since all of these are going through the `slog`, we can use our own custom handler to drop records with specific prefixes.
I believe there are some talks happening with the `osv-scalibr` team to see if some of these can be toned back, and also I think we will probably want to capture some of these at some point as part of valid tests, but short-term this should help make things more manageable.
I'm opening this as a draft as I don't know if we do actually want to land this, in part because I think this is going to almost immediately break as we've switching to `slog` ourselves which involves using a custom `slog` handler meaning this one will get overridden, but I still wanted to …
=> test: reduce noise in cmd cases using a custom `slog` handler

README.md, cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/main_test.go, docs/guided-remediation.md, docs/license-scanning.md, docs/offline-mode.md, docs/usage.md
This PR moves the `--licenses` and `--all-packages` flags out of experimental mode. Along with [PR 1668](https://github.com/google/osv-scanner/pull/1668), all our flags are now out of experimental mode.
=> feat: move license scanning and all package flags out of experimental

cmd/osv-scanner/__snapshots__/main_test.snap, internal/output/table.go
While prototyping some changes to help with #1567, I discovered that the table output format is not explicitly sorting vulnerabilities across their groups, meaning we're assumingly using the order that the API gives us, and means our current output does not actually follow a predictable order.
To address this, I've modified the table outputter to sort vulnerability groups by the first ID in each group as a group by definition will always have at least one ID and the first ID should be the one primary one since we already sort ids within each group as part of building the general results
=> fix(output): ensure that vulnerabilities are sorted by ID across groups in table output

.golangci.yaml, cmd/osv-scanner/fix/noninteractive.go, cmd/osv-scanner/fix/state-choose-strategy.go, cmd/osv-scanner/fix/state-in-place-result.go, cmd/osv-scanner/fix/state-relock-result.go, internal/clients/clientimpl/osvmatcher/cachedosvmatcher.go, internal/datasource/npm_registry.go, internal/datasource/npm_registry_cache.go, internal/grouper/grouper.go, internal/output/result.go, internal/remediation/in_place.go, internal/remediation/in_place_test.go, internal/remediation/suggest/maven.go, internal/remediation/testhelpers_test.go, internal/resolution/lockfile/npm_v2.go, internal/tui/dependency-graph.go, pkg/osvscanner/osvscanner.go, scripts/generate_mock_resolution_universe/main.go
These became stable in Go v1.21, so we can stop using the `x/exp` versions
(this will be enforced by the `expotostd` linter which is being introduced in the next version of golanglint-ci)
=> refactor: replace experimental libraries with their std versions

experimental/javareach/cmd/reachable/main.go
Parse /META-INF/services/ correctly by handling cases like files defining `class = org.jline.terminal.impl.exec.ExecTerminalProvider` and `sun.io.StandardCodec # Standard codecs for the platform`
=> fix(javareach): parse `/META-INF/services/` correctly

renovate.json
Renovatebot PR seems to be failing because of the constraint.
=> fix: Update constraint to not be pinned to minor version

experimental/javareach/cmd/reachable/main.go, experimental/javareach/reachable.go
Classes defined in META-INF/services might not exists in the JAR.
=> fix(javareach): handle cases where META-INF/services classes can't be found

.golangci.yaml
There's no actual linting violations currently in the `internal/thirdparty/ar` package, but we might as well exclude all packages 🤷
=> chore: exclude all third-party packages from linting

.golangci.yaml, scripts/run_lints.sh
This should help ensure that linting results are consistent regardless of how the linter is being run
=> chore: configure `golangci-lint` to always show all issues from all linters

.golangci.yaml, internal/datasource/maven_registry.go, internal/datasource/npm_registry_test.go, internal/resolution/client/client.go, internal/sourceanalysis/rust.go
This matches what I think is the general preference these days - either way, consistency is good and I don't know of a `use-interface` rule 😄
=> refactor: use `any` instead of `interface{}`

experimental/javareach/cmd/reachable/main.go, experimental/javareach/jar.go, experimental/javareach/javaclass.go
Fixes a bunch of Java readability issues:
- remove `com/` from stdlib prefixes
- exit program with errors if running against a non maven JAR
- handle wrapped class names in the manifest file
- replace some non-fatel error messages with debug messages to reduce noise
=> fix(javareach): maven validation and correct manifest class name parsing

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/image/main.go
Note: Merge #1734 first, otherwise review only the latest commit.
This checks if the image passed in has a tag, because if there is no tag, it risks multiple images to be saved, resulting in a weird error message for the user.
=> feat: Force tag to be used when scanning image

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/locks-scalibr/packages.config, cmd/osv-scanner/fixtures/locks-scalibr/packages.lock.json, cmd/osv-scanner/main_test.go, docs/supported_languages_and_lockfiles.md, pkg/osvscanner/internal/scanners/extractorbuilder.go, pkg/osvscanner/internal/scanners/lockfile.go
This PR adds more lockfile extractors supported in OSV-Scalibr for .NET:
- `packages.config`
- `packages.lock.json`
=> feat: Add support for more .NET extrators

cmd/osv-scanner/fix/state-choose-strategy.go, cmd/osv-scanner/fix/state-in-place-result.go, cmd/osv-scanner/fix/state-relock-result.go, docs/github-action.md, docs/guided-remediation.md, docs/migration-guide.md, docs/output.md, docs/supported_languages_and_lockfiles.md, docs/usage.md, internal/ci/vulnerability_result_diff.go, internal/clients/clientimpl/osvmatcher/cachedosvmatcher.go, internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/customgitignore/dir_test.go, internal/customgitignore/walk_up_to_root.go, internal/datasource/http_auth.go, internal/output/sarif.go, internal/output/sbom/cyclonedx_common.go, internal/resolution/dependency_subgraph.go, internal/resolution/resolve.go, internal/sourceanalysis/rust.go, internal/testutility/mock_http.go, internal/utility/purl/package_grouper.go, internal/utility/semverlike/version-semver-like.go, scripts/generate_mock_resolution_universe/main.go
These were flagged by my IDE, so I figured I'd get them addressed
=> docs: minor grammar fixes

scripts/build_snapshot.sh
This was changed in v2: https://goreleaser.com/deprecations/#-rm-dist
=> chore: update snapshot script for `goreleaser` v2

cmd/osv-reporter/main.go
Printing an error results in a 127 return code, when we want to return 0 when these warnings happen. This fixes a unintented behaviour change made as part of the slog refactor.
Fixes https://github.com/google/osv-scanner-action/issues/65
=> fix: osv-reporter should be print a warning instead of an error for these messages

docs/supported_languages_and_lockfiles.md, pkg/osvscanner/internal/scanners/extractorbuilder.go
Enable the cargoaudit extractor in container scanning
=> feat: Add cargoaudit extractor to artifacts

scripts/build_test_images.sh
This should make it easier to ensure that you've got the same images as in CI - it'd be good if someone on macOS could test these for me, as opt-parsing has a bit patchy between OSs
Usages:
```
scripts/build_test_images.sh --force
scripts/build_test_images.sh --no-cache
scripts/build_test_images.sh --force --no-cache
```
=> chore: add `--force` and `--no-cache` flags to script for building test images

.golangci.yaml, cmd/osv-scanner/fix/testmain_test.go, cmd/osv-scanner/internal/cmd/testmain_test.go, cmd/osv-scanner/scan/image/testmain_test.go, cmd/osv-scanner/scan/testmain_test.go, cmd/osv-scanner/testmain_test.go, cmd/osv-scanner/update/testmain_test.go, internal/ci/testmain_test.go, internal/datasource/testmain_test.go, internal/output/testmain_test.go, internal/remediation/testmain_test.go, internal/resolution/lockfile/testmain_test.go, internal/resolution/manifest/testmain_test.go, internal/resolution/testmain_test.go, internal/sourceanalysis/testmain_test.go, pkg/models/testmain_test.go, pkg/osvscanner/testmain_test.go
Apparently since Go v1.15 `os.Exit` will be called automatically by the runner with the result of `m.Run` if a call to exit has not been made when `TestMain` finishes, so we can omit doing it ourselves
=> test: remove redundant `os.Exit` calls

cmd/osv-scanner/scan/__snapshots__/command_test.snap, cmd/osv-scanner/scan/command_test.go, pkg/osvscanner/internal/scanners/lockfile.go, pkg/osvscanner/scan.go
I'm open to suggestions about the actual message - I'm a little on the fence about including a list of the file types or external links as they could change (and CycloneDX also has `bom.json` and `bom.xml` meaning it's technically not as easy as saying "it must end with these file types"), but maybe that's worth doing...
I think ideally it would be good if `osv-scalibr` could indicate the reason why the extractor can't be found, but I don't think that's compatible with the current API and also somewhat niche.
Resolves #1746
Relates to #1745
=> fix: include a hint when sbom extractor cannot be found about the file name being important

.goreleaser.yml
Noticed #1742 had accidentally been reverted
```
• setting defaults
• DEPRECATED: archives.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• DEPRECATED: archives.builds should not be used anymore, check https://goreleaser.com/deprecations#archivesbuilds for more info
```
=> build: move off deprecated archives.format and archives.builds properties again

internal/thirdparty/xml/marshal_test.go, internal/thirdparty/xml/xml.go
Double quotes are still escaped when marshaling text fields in XML, and we don't want that behavior.
=> feat(xml): do not escape double quotes

cmd/osv-scanner/scan/__snapshots__/command_test.snap, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go
https://github.com/google/osv-scanner/issues/1794
Previously the license overrides are not reflected in the scan results so the license summary is based on the licenses before overriding. This PR fixes the issue by updating the package scan result with the license overrides.
=> fix: override licenses in scan results

docs/supported_languages_and_lockfiles.md
This PR updates the documentation on the "Supported Artifacts and Manifests" page to accurately reflect the current support status for Maven Central and private registries.
The existing documentation stated that support for private registries was "coming soon." This information is outdated, as OSV-Scanner now supports querying these registries alongside the default deps.dev API. This change ensures users have accurate information about OSV-Scanner's capabilities.
- Modified the file: `docs/supported_languages_and_lockfiles.md`
- Replaced the sentence:
`The support for private registries is coming soon.`
with:
`Support for querying Maven Central and private registries is also available.`
https://s-index.github.io/osv-scanner/supported-languages-and-lockfiles/
=> docs: Update Maven Central and private registries support

cmd/osv-scanner/scan/source/command.go
Since `append` does not modify the target slice itself, it's safe to use the command-specific scan flags slice as the target for adding the global flags, which lets us avoid a bit of faff with preallocation and calling the function twice, and makes us consistent with the `image` commands implementation
=> refactor: avoid repeated call to get scan global flags

internal/scalibrextract/ecosystemmock/extractor.go, internal/scalibrextract/filesystem/vendored/vendored.go, internal/scalibrextract/language/javascript/nodemodules/extractor.go, internal/scalibrextract/vcs/gitrepo/extractor.go
This is mainly about removing the duplicate check we have in most extractors, though I've also favored the check itself being at the bottom to be consistent with `osv-scalibr`
=> refactor: ensure all extractors have a single interface check at the bottom of the file

.golangci.yaml, cmd/osv-scanner/fix/command_test.go, cmd/osv-scanner/internal/cmd/helpers_test.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/image/command_test.go, cmd/osv-scanner/update/command_test.go
Thanks to #1798 we can now blanket require that all tests are run in parallel with the linter, which has also revealed a few existing cmd tests that were not made parallel
=> test: ensure that all tests are run in parallel

renovate.json
We are now no longer staying on the older release of go, so no need for the constraint (and it also breaks renovatebot right now)
=> chore: Remove renovatebot constraint

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
They added CVSS scores to the libxml advisory
=> chore: Update snaps again

cmd/osv-scanner/fix/testmain_test.go, cmd/osv-scanner/internal/cmd/run.go, cmd/osv-scanner/internal/testcmd/run.go, cmd/osv-scanner/main.go, cmd/osv-scanner/scan/image/command_test.go, cmd/osv-scanner/scan/image/testmain_test.go, cmd/osv-scanner/scan/source/command_test.go, cmd/osv-scanner/scan/source/testmain_test.go, cmd/osv-scanner/scan/testmain_test.go, cmd/osv-scanner/testmain_test.go, cmd/osv-scanner/update/command.go, cmd/osv-scanner/update/testmain_test.go
Currently because all commands are included in all `cmd` tests any code change will invalid the test cache for all `cmd` packages regardless of if the change is actually impactful to them - we can avoid this by having the setup for each `cmd` package explicitly set the commands to include in the test, as the cost of a minor change to the app builder function
=> test: only include specific command under test in `cmd` package tests

cmd/osv-scanner/fix/testmain_test.go
I forgot to change this when doing #1737, as the `fix` tests were originally in the package itself
=> test(fix): use public package

.github/workflows/checks.yml
Currently we're actually just testing the Linux AMD64 `osv-scanner` image, but it's still better than nothing
=> ci: add job to ensure that Docker image should work

cmd/osv-scanner/fix/__snapshots__/command_test.snap, cmd/osv-scanner/fix/fixtures/override-maven/pom.xml, internal/resolution/manifest/maven.go
Currently we use the common indentation when writing `<dependency>` elements. This PR improves the writer behaviour by getting the indentation of the first `<dependency>` element in dependencies so the newly added XMLs are more readable.
=> feat: guess the indentation for <dependency> element when writing XML

internal/output/helpers_test.go
This field is required in `osv-scalibr` v0.2.1+ when building SPDX SBOMs or otherwise the package will be skipped:
```
❯ go test ./internal/output/... -count 1 -run 'TestPrintSPDXResults_WithVulnerabilities/one_source_with_one_package_and_one_vulnerability'
2025/05/22 14:36:42 Package &{mine1 1.2.3 <nil> [path/to/my/first/lockfile]  {<nil> 0} [] <nil> <nil>} has no PURL, skipping
2025/05/22 14:36:42 Package &{mine1 1.2.3 <nil> [path/to/my/first/lockfile]  {<nil> 0} [] <nil> <nil>} has no PURL, skipping
```
=> test(output): include `PURLType` field in fixtures

.github/workflows/checks.yml
While we generally shouldn't have any vulnerabilities, it does sometimes happen due to merge delays or false positives, so we shouldn't fail this job as a result of that as it's just using our root `go.mod` to verify the image is working.
Note that by default GitHub Actions runs inline commands with `bash -e` meaning we need to extract the exit code on the same line rather than getting it afterwards
=> ci: only fail `docker` job if we get a non-zero exit code that does not mean "no vulns found"

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go
Among other things, this covers the fact that we currently check if we're offline _after_ we validate the licenses since we could flip that to simplify our implementation but currently doing so would not reveal that it changes our behaviour
=> test(scan): add license cases for when invalid and offline

docs/configuration.md, docs/contribute.md, docs/experimental.md, docs/github-action.md, docs/guided-remediation.md, docs/installation.md, docs/license-scanning.md, docs/offline-mode.md, docs/output.md, docs/scan-image.md, docs/scan-source.md, docs/supported_languages_and_lockfiles.md, docs/usage.md
Since Jekyll uses the first header element it finds in the markdown as the title, we don't need to repeat it in the frontmatter of every doc
=> docs: make headers and titles consistent

docs/offline-mode.md, docs/scan-source.md, docs/usage.md
These have slipped through recently as the link checker workflow only runs on modified files for pull requests
=> docs: update broken links

docs/output.md, docs/scan-image.md, docs/usage.md
Let me know if there's any discussion links we're like to restore
=> docs: remove references to v2 beta

.prettierignore
These don't need to be formatted
=> chore: have Prettier ignore generated sites files

.github/workflows/snapshots.yml
Make the commit pretending to be me, let's test if this actually works to trick the CLA.
Example of it sort of working on my fork: https://github.com/another-rex/osv-scanner/pull/19
=> test: Pretend to be me

.golangci.yaml, cmd/osv-scanner/main_test.go
Fix the version and help output not being thread safe by avoiding parallel for that test.
Reasoning:
cli.VersionPrinter is a global variable that gets overwritten every .Run call with a new function. I'm still not too clear on why that would cause the logs to be messed up though.
=> test: Don't parallel the one test that can't be parallel

.github/workflows/snapshots.yml
I believe the current action we're using doesn't recreate the branch with enough force meaning we can end up with old snapshot content from bugs that have since been fixed - based on what I've seen of the source code, I think `peter-evans/create-pull-request` should do a better job as it sounds like it will actually try recreating the branch fresh rather than always starting on the existing branch
=> ci: use a different action

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go
I'm just going to assume this was because my extractors implementation predated when I moved the fixtures around 😅 
Relates to #1920 and #1896
=> test(cmd): use package-local fixtures for extractor cases

CONTRIBUTING.md, README.md, docs/guided-remediation.md
* `CONTRIBUTING.md`: this link is not expected to exist, as it's an example with a placeholder
* `README.md`: technically it's an absolute URL, but it's in HTML and ultimately I didn't want to mess with it since GitHub and IntelliJ both seem to resolve it correctly
* `docs/guided-remediation.md`: the hash is rendered by the `.note` helper which the checker cannot understand
=> chore: disable link checker for some specific links

.golangci.yaml, internal/identifiers/identifiers.go, internal/resolution/lockfile/lockfile.go, internal/resolution/manifest/manifest.go
This makes the code more readable by reducing duplicate operators
=> refactor: use tagged switches

internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/clients/clientimpl/osvmatcher/osvmatcher_test.go
The `MatchVulnerabilities` method in `osvmatcher.go` could panic when accessing `batchResp.Results` if `batchResp` is nil.
- Added nil check for `batchResp` before accessing its `Results` field
- Added test case `"Timeout returns deadline exceeded error"` to verify the timeout behavior
- Test ensures the method returns `context.DeadlineExceeded` error without panicking
- `internal/clients/clientimpl/osvmatcher/osvmatcher.go`: Added nil check and documentation
- `internal/clients/clientimpl/osvmatcher/osvmatcher_test.go`: New test file with timeout test case
=> fix: prevent panic when batchResp is nil in MatchVulnerabilities

.github/workflows/checks.yml
A large amount of CI time for the Windows "test suite" is actually spent extracting the module cache to the point that I suspect it might be faster to skip caching - to test this, I'm adding a new job that runs our tests on Windows without the cache so that after a few months we'll be able to compare the average runtime of the jobs in the metrics tab:
=> ci: add job to see how fast Windows tests run without a cache

docs/github-action.md
This flag was removed in v2 in favor of `--include-git-root` which is an opt-in flag so doesn't need to be added here
=> docs: remove reference to v1 flag

.github/workflows/snapshots.yml
Any test failure that isn't fixed by (re)generating the snapshots should be present in the CI for the resulting pull request and if there are snapshot updates needed having those already generated will save some work - for example, the workflow is currently failing because one of our tests needs its exit code updated as previously it didn't have any vulnerabilities
=> ci: create snapshots pull request even if tests fail

cmd/osv-reporter/main.go, cmd/osv-scanner/internal/cmd/run.go, cmd/osv-scanner/scan/source/command_test.go, internal/cmdlogger/handler.go, internal/cmdlogger/interface.go, internal/testlogger/handler.go
This has us output a dedicated exit code in the event of an invalid configuration file to make it easier to identify those situations in an automated context.
Because we ignore invalid configs rather than hard erroring, supporting this has required adding a new method to our logger interface for tracking if we errored specifically because of an invalid config - while this might seem strange, I think it's actually fine because this is all internal code and it should be straightforward to make it more generic _if_ we find further need for this sort of thing (also tying in somewhat to doing more structured logging)
Relates to https://github.com/google/osv-scanner/issues/1221#issuecomment-2873896420
=> feat: use a dedicated exit code when a config is invalid

cmd/osv-scanner/internal/helper/helper.go, cmd/osv-scanner/scan/image/command.go, cmd/osv-scanner/scan/source/command.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result_internal_test.go
These fields were marked as stable as part of the v2 release but we forgot to move the actual struct fields out of the experimental struct, which this does.
Technically this isn't breaking because we declare anything in the experimental struct as not being covered by semver 😅
=> feat: make various experimental fields as stable

cmd/osv-scanner/scan/source/command.go
We have to use this field to maintain backwards compatibility
=> chore: ignore use of our own deprecated field

.github/workflows/goreleaser.yml
This pull request resolves Issue #1976 
Minor change to add a prefix `v` to stable container image tags because images are tagged 
in this format `v1.0.0` instead of `1.0.0`.
=> feat: Adding prefix v to stable tag image (#1976)

cmd/osv-reporter/main.go, docs/osv-reporter.md, docs/scan-image.md
Playing around with output formats for the reporter, perhaps we introduce it to osv-scanner --output flag in the future to allow for multiple outputs.
=> feat: Experimental output format for reporter

cmd/osv-scanner/fix/command.go, internal/imodels/imodels.go, internal/remediation/in_place.go, internal/remediation/override.go, internal/remediation/remediation.go, internal/resolution/client/depsdev_client.go, internal/resolution/client/override_client.go, internal/resolution/manifest/manifest.go, internal/resolution/manifest/maven.go, internal/resolution/resolve.go, internal/testutility/mock_http.go, pkg/osvscanner/osvscanner.go
This will be enforced by the `embeddedstructfieldcheck` linter introduced in v2.2
=> refactor: place embeds at the start of structs followed by a newline

cmd/osv-scanner/internal/helper/helper.go
I'm guessing this slipped in through a manual find-and-replace 😅
=> fix: use natural language in extractors flag descriptions

cmd/osv-scanner/scan/image/command_test.go
Looks like these started working on Windows at some point likely as a result of the refactoring we've done to the JSON and snapshot normalization handling 🤷
=> test: run JSON format image cases on Windows

cmd/osv-scanner/scan/image/__snapshots__/command_test.snap, cmd/osv-scanner/scan/image/command_test.go
Only one of these tests actually uses `--all-packages` but they all output in JSON format so I think this is a better name and that also means its reasonable for us to add more cases such as in #2021
=> test: rename `scan image` JSON format cases

.golangci.yaml, internal/resolution/dependency_subgraph.go
Import aliases should follow the same conventions as package names for consistency, though for our single violation we don't actually need an alias in the first place
=> refactor: follow package naming conventions for import aliases

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, internal/builders/extractors.go
This should make it easier to enable support for extractors as they're shipped in `osv-scalibr`, though it does come at the cost of making it more opaque what extractors consumers can provide but we can deal with that problem at a later date especially since the CLI side is still experimental
=> refactor: use scalibr function for building extractors by name

cmd/osv-scanner/scan/image/__snapshots__/command_test.snap, go.mod, go.sum, internal/image/fixtures/ubuntu20-04-unimportant-config.toml, internal/utility/severity/severity.go, pkg/osvscanner/vulnerability_result.go
Resolves https://github.com/google/osv-scanner/issues/1964
Note: some Ubuntu records have moved their priority tags from ecosystem-specific to severity fields, but osv.dev has failed to provide a correct severity type. For now, we check both empty severity tags and Ubuntu severity tags to see if a vulnerability has been marked as ineligible
=> feat: support ubutnu severity type

.github/workflows/osv-scanner-reusable-pr.yml, .github/workflows/osv-scanner-reusable.yml
I realized that instead of emitting a warning we can just have the action error, and use [workflow summaries](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-job-summary) to show a nice message pointing at the replacement action 😄
=> ci: have reusable workflows error

internal/testlogger/handler.go
The runtime.AddCleanup function can emit logs, which we are not accounting for. Rather than panicing, I think we should just emit all these weird instances onto stdout/err.
Example:
https://github.com/google/osv-scanner/actions/runs/16135059021/job/45529700263?pr=2036
=> test: There are things other an goroutines that can emit logs

pkg/osvscanner/scan.go
The `OSUnix` value is only meant to be used by plugins to indicate they're fine working with either Linux or macOS, but [the OS still needs to be one of those values](https://github.com/google/osv-scalibr/blob/ed2676c6ae1b/plugin/plugin.go#L119-L125) when scanning.
This is not an issue currently because we're just using extractors, but there are a few detectors that require a Unix-like OS
=> fix: properly flag if running on Linux or Mac OSs

internal/output/__snapshots__/output_result_test.snap, internal/output/output_result.go
This field is not used by anything and we already have the ecosystem available as the map key, so this is just wasting memory
=> refactor(output): remove unused `Ecosystem` field

.github/workflows/checks.yml
Sadly all this has ended up doing is providing the cache is saving us around 20 seconds of time 😢
=> ci: remove "windows tests with no cache" job

.golangci.yaml
These functions have long since gone, and the package itself now is internal
=> chore: remove old public `reporter.Reporter` config

pkg/models/results.go
These branches are not covered by our test suite indicating we've either got some missing cases or they're not actually needed - I'm betting on it being the latter, and if I'm wrong then we'll have found a hole
=> refactor(models): remove unneeded group IDs length check

internal/clients/clientimpl/localmatcher/localmatcher.go, internal/clients/clientimpl/osvmatcher/osvmatcher.go, internal/imodels/imodels.go, internal/remediation/override.go, internal/remediation/suggest/maven.go, internal/sourceanalysis/rust.go
This gets rid of a couple of todos and overall makes things a bit more consistent - we still have uses of `log.Fatalf` and `log.Panicf` as we don't have `cmdlogger` versions of those, which might be worth doing just for further consistency
=> refactor: use `cmdlogger` instead of `log`

go.mod, go.sum
This should enable Renovate to automatically update us to the latest version of `osv-scalibr` on `main` - the actual commit I've used is for the one immediately after v0.3.1 as I couldn't get Go to use that exact commit (it seems to check for tags against the commit, and prefer those instead)
=> feat: switch to the commit version of `osv-scalibr`

cmd/osv-scanner/scan/image/command_test.go, internal/cmdlogger/handler.go, pkg/osvscanner/osvscanner.go
=> feat: Allow log handler overriding

cmd/osv-scanner/internal/helper/getters.go, cmd/osv-scanner/scan/image/command.go, cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command.go, internal/scalibrplugin/detectors_parser.go, internal/scalibrplugin/detectors_parser_test.go, internal/scalibrplugin/extractors_parser.go, internal/scalibrplugin/extractors_parser_test.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/scan.go
This puts the API of our CLI and public package back in sync and make it easier to build on since we should not have to do as much double-handling.
As this is expected to be one of a couple of changes to this aspect of the scanner, I've introduced the `scalibrplugin` package as part of this which I expect to eventually house stuff like our presets and builder related code
=> feat: move resolving extractors from names into `osvscanner`

renovate.json
I think this is needed because we are already grouping dependencies in the `golang` category into a group, so by having an explicit group name for this package rule it should cause them not to get merged
=> ci: put `osv-scalibr` updates in their own group

docs/_sass/color_schemes/_variables.scss, docs/_sass/color_schemes/custom_dark.scss, docs/_sass/highlight/native.scss
This PR adjusts the Callout block colors for better visibility, most notably affecting the highlight callouts on the [guided remediation page](https://google.github.io/osv-scanner/experimental/guided-remediation/)
Resolves #1291
=> style(docs): Improve theme styling for Jekyll highlight blocks

go.mod, go.sum
It seems if you use 0.0.0 for a pseudo version, then renovate will want to upgrade to the latest tagged version rather than the latest digest, and that there's generally no explicit way to force renovate to only use digests.
I expect this means we'll need to adjust this again once the next version of osv-scalibr is tagged, but for now we can just set the version back to v0.3.2 🤷
=> chore: adjust pseudo constraint for `osv-scalibr`

scripts/report_uncleaned_snapshots.py
Currently if you have a directory with `__snapshots__` but no tests, our script will crash - while it shouldn't be possible for this to happen on `main`, I think its good for us to handle since it can happen locally especially if you're switching between branches that add and remove packages
=> chore: don't crash for packages without test files

internal/clients/clientimpl/localmatcher/localmatcher.go
The results from `MatchVulnerabilities` is expected to have the same items as packages that were provided but currently if the database cannot be loaded (such as because we're using an ecosystem that does not have a database available) we just "continue" resulting in off-by-n errors further down the line
=> fix(local): log and preserve package count before continuing on db error

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, pkg/osvscanner/scan.go
This should help make things easier to maintain as it pushes us a little further towards having a single blob of extractors/plugins rather than needing to manage multiple conditions based on what (sub)type of scanning we're doing.
Right now this code path only comes into play when using the scanner package directly without passing any extractors, but once #2100 is landed (which pulls the extractor building into the scanner package itself) we'll be using this path more
=> fix: only get and configure extractors once

cmd/osv-scanner/scan/image/__snapshots__/command_test.snap, pkg/osvscanner/osvscanner.go
Turns out container scanning is not using absolute paths in its results, which isn't breaking anything but is an assumption of our `output` package
=> fix: store absolute paths when scanning containers

cmd/osv-scanner/scan/source/testmain_test.go, cmd/osv-scanner/scan/testmain_test.go, cmd/osv-scanner/testmain_test.go, go.mod, go.sum, internal/testutility/utility.go
[`go-snaps` have added support](https://github.com/gkampitakis/go-snaps/issues/130) for signaling if there are dirty snapshots or if there was an issue with cleaning snapshots, so now our snapshot clean utility function will fail the tests if that is the case.
It feels a little meh to be doing an `os.Exit` in a function like this but the alternative would be to do this in every `TestMain` that uses snapshots, and we only have three packages whose `TestMain` does something after cleaning snapshots so its probably fine (for now at least)
=> test: fail if there are dirty snapshots or if there is an issue cleaning snapshots

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go, cmd/osv-scanner/scan/source/fixtures/locks-insecure/osv-scanner.json, internal/imodels/imodels.go, internal/scalibrextract/language/osv/osvscannerjson/extractor.go, internal/scalibrextract/language/osv/osvscannerjson/extractor_test.go
Fixes #2139 
Since osv-scalibr updated how Ecosystem is returned to be centralized, we need to add our own check in imodels to return the correct ecosystem.
Also:
- Removed extra functions in the extractor that's no longer needed
- Added a test for the regression.
=> fix: osv-scanner json scans not matching with correct ecosystem

cmd/osv-scanner/scan/image/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go, cmd/osv-scanner/scan/source/fixtures/locks-scalibr/Podfile.lock, internal/imodels/ecosystem/ecosystem.go, internal/scalibrplugin/__snapshots__/resolve_test.snap, internal/scalibrplugin/presets.go, pkg/osvscanner/filter.go
Fixes: #2151
It looks like osv.dev will return invalid ecosystem for all queries in a batchquery if 1 query has an invalid ecosystem. This means we have to add a check in osv-scanner to prevent any invalid ecosystems from being sent. 
This does mean if we release osv-scanner with extractors to support future ecosystems that are currently invalid, people will have to update to get support for those ecosystems when supported in osv.dev in the future, instead of being able to use existing version of osv-scanner. I don't think this is a common case, so this is acceptable.
Changes in this PR:
- Added Podfile.lock to test cases, should return 127 if scanned alone
- Excude Podfile.lock and Package.resolved because we don't support the Swift Cocoapods ecosystem  (SwiftURL is for the Swift package …
=> fix: invalid ecosystem error

go.mod
Update go mod go version to resolve vuln detected by osv-scanner (in sql, so does not affect us that much, but nice to update anyway)
=> chore: Update gomod go version to 1.24.6

cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go, cmd/osv-scanner/scan/source/testdata/sbom-insecure/only-unimportant.spdx.json, internal/output/table.go, pkg/osvscanner/osvscanner.go
Fixes #2201 
Fixes #1975
There's a bug with the original implementation of the --all-vulns flag, where when scanning OS packages in non container scanning mode, it would not correctly hide unimportant packages. This fixes that issue and adds some test cases to confirm the fix.
=> fix: unimportant vulns returning 1 error code when not image scanning

cmd/osv-scanner/internal/helper/flags.go, cmd/osv-scanner/internal/helper/getters.go, cmd/osv-scanner/scan/image/__snapshots__/command_test.snap, cmd/osv-scanner/scan/image/command_test.go, cmd/osv-scanner/scan/source/__snapshots__/command_test.snap, cmd/osv-scanner/scan/source/command_test.go, docs/manual-plugin-selection.md, docs/migrating-from-scalibr.md, pkg/osvscanner/osvscanner.go, pkg/osvscanner/scan.go
=> feat: make `--plugins` additive by default, and introduce `--no-default-plugins`

.github/workflows/snapshots.yml
Since the team is based in AU & NZ, there's a good 4-6 hours min. before a snapshot update PR will get looked at let alone merged during which time further advisory changes might occur.
Having the workflow run later in the AU/NZ morning will hopefully reduce a few of the (re)runs
=> ci: update snapshots earlier in the AU/NZ morning

internal/scalibrextract/filesystem/vendored/vendored.go, internal/scalibrextract/vcs/gitrepo/extractor.go, internal/scalibrextract/vcs/gitrepo/extractor_test.go, pkg/osvscanner/scan.go
Rather than configuring our internal plugins to be disabled, we can just explicitly add them to the disabled plugins list as part of fetching the plugins; we also don't need to support not including the git root in the `gitrepo` extractor since we always disable the plugin if that option is not enabled
=> refactor: simplify internal plugin disabling and configuration

.github/workflows/dependencies.yml
As running the tests involves compiling Go, it'll error if a change in scalibr causes a compile-time error which is exactly why we're wanting this workflow in the first place so we should be continuing regardless of if the running-of-tests step is successful 😅
=> ci: create pr for updating scalibr even if tests fail

.github/workflows/checks.yml
This should ensure that files are valid across OSs - I've gone with an inclusive pattern which purposely does not have some characters that are technically legal but that I don't think there's a good reason to use them in a filename.
=> ci: ensure filenames don't have undesired characters
