google/osv-scanner

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yaml
- LICENSE
- renovate.json
- Set token permissions for github actions
- Add LICENSE
- Add renovate.json
> Multiple changes to improve scorecard:

- pkg/lockfile/parse.go
> Change path to filepath to work with windows type paths

- README.md
- internal/grouper/grouper.go
- internal/grouper/grouper_test.go
- internal/output/reporter.go
- internal/output/table.go
- pkg/models/results.go
- pkg/osvscanner/osvscanner.go
- pkg/osvscanner/vulnerability_result.go
- pkg/osvscanner/vulnerability_result_test.go
Write out grouped JSON field as proposed here: #29, also changes osvscanner library interface to also output these groups.
> Group json output

- README.md
Point them to the tracking issues for supporting transitive deps.
> Update fineprint for requirements.txt and pom.xml

- cmd/osv-scanner/main.go
- pkg/osvscanner/osvscanner.go
> Fixed #52 - Raise exit code properly on vulnerabilities.

- README.md
Change the indentation a bit and update ToC.
> Minor updates to install instruction title

- .gitignore
- CONTRIBUTING.md
- README.md
Fixes #122 . Not sure if install from source should be moved to contributing as well, but I'm leaning towards leaving it in README since people might have go and just want to install it from there.
> Add contributing file

- CHANGELOG.md
- pkg/lockfile/apk-installed_test.go
Update the changelog for v1.1.0. After merge this will probably be the commit to be tagged v1.1.0
> v1.1.0 release PR

- .github/workflows/goreleaser.yml
Add write packages perm to allow pushing docker images
> Fix goreleaser permissions

- cmd/osv-scanner/main_test.go
> test: add case for `--version` flag

- internal/semantic/parse_test.go
Port of https://github.com/G-Rath/osv-detector/pull/167
> test: add cases for `semantic.MustParse`

- action.yml
Related to #170
Adds a simple comment to explain that the current action is experimental.
> Add experimental comment for our github action

- USAGE.md
- pkg/osvscanner/osvscanner.go
@oliverchang pointed out a few things #206 after it was merged
> Minor changes for gitignore parsing

- pkg/lockfile/fixtures/maven/interpolation.xml
- pkg/lockfile/fixtures/maven/with-dependency-management.xml
- pkg/lockfile/parse-maven-lock.go
- pkg/lockfile/parse-maven-lock_test.go
> feat: support `dependencyManagement` in Maven poms

- docs/_config.yml
The previous ID was not correct.
> Update analytics for documentation.

- go.mod
- go.sum
- pkg/lockfile/parse-pnpm-lock.go
- pkg/lockfile/parse-pubspec-lock.go
Update to yaml.v3, all tests still pass. Closes #118
> Upgrade to yaml v3

- docs/current/output.md
- docs/current/usage.md
- docs/working_docs/usage.md
You can preview the docs here: https://hayleycd.github.io/osv-scanner/
Updating docs for the new release.
> Moving Working Docs to Current

- docs/current/installation.md
- docs/working_docs/installation.md
Preview changes [here](https://hayleycd.github.io/osv-scanner/installation/)
Added instructions for Alpine Linux and OpenBSD.
> Adding additional installation instructions

- internal/sbom/cyclonedx.go
> Parse nested CycloneDX components correctly

- .github/workflows/lint.yaml
- Dockerfile
- goreleaser.dockerfile
Pin lint action as recommended by scorecard. Also pins docker files
> Pin lint action

- .github/workflows/goreleaser.yml
Attempt to run tests before a release.
> Run tests before release

- pkg/models/vulnerability.go
- add omitempty to more optional fields.
- correct severity, which is an array.
> Fix some issues with the model.

- cmd/osv-scanner/fixtures/sbom-insecure/osv-scanner.toml
- cmd/osv-scanner/main_test.go
- internal/govulncheckshim/fixtures/test-project/osv-scanner.toml
This should fix the scorecard vulnerabilities alert false positive.
> Add configs to ignore test vulnerabilities

- docs/usage.md
The callout that stressed that call analysis is an experimental feature was not rendering correctly. I have fixed it. 
I would appreciate if this change could be merged to the docs branch in the next day or so, because there is a blog going out soon that mentions the govulncheck integration.
> Call analysis note fixed. 

- renovate.json
Enable the experimental osvVulnerabilityAlerts feature for renovate bot.
> Enable osvVulnerabilityAlerts

- pkg/lockfile/fixtures/pnpm/empty.yaml
- pkg/lockfile/fixtures/pnpm/no-packages.yaml
- pkg/lockfile/parse-pnpm-lock.go
- pkg/lockfile/parse-pnpm-lock_test.go
Copied from G-Rath/osv-detector#191
Co-authored-by: Gareth Jones <Jones258@Gmail.com>
fixes: #364
> fix: don't panic on empty  files

- docs/output.md
I fixed the table for the exit docs. Please see #373 for the code changes. 
[Preview changes here](https://hayleycd.github.io/osv-scanner/output/#return-codes)
> Update exit docs

- cmd/osv-scanner/main.go
- cmd/osv-scanner/main_test.go
- docs/output.md
- pkg/reporter/table_reporter.go
> Improve exit docs and add No vulns found to output

- cmd/osv-scanner/main.go
- pkg/osv/osv.go
- pkg/osvscanner/osvscanner.go
Add a user agent to osv-scanner OSV API requests to help see usage and and help with debugging slow queries.
Closes #388
> OSV user agent

- cmd/osv-scanner/main.go
- cmd/osv-scanner/main_test.go
Added back in the change made in #166
> Fix version printer to use app stdout and stderr

- pkg/models/constants.go
- pkg/models/vulnerability.go
- Adds "related" field.
- Adds constants for Rocky Linux and AlmaLinux.
- Add new reference types "DETECTION", "DISCUSSION", and "INTRODUCED"
> Update the model to match the latest version of the OSV schema

- .golangci.yaml
- internal/semantic/compare_test.go
- internal/semantic/parse_test.go
- pkg/lockfile/csv_test.go
- pkg/lockfile/helpers_test.go
- pkg/lockfile/parse-cargo-lock.go
- pkg/lockfile/parse-cargo-lock_test.go
- pkg/lockfile/parse-composer-lock_test.go
- pkg/lockfile/parse-gemfile-lock_test.go
- pkg/lockfile/parse-go-lock.go
- pkg/lockfile/parse-maven-lock_test.go
- pkg/lockfile/parse-mix-lock_test.go
- pkg/lockfile/parse-npm-lock-v1_test.go
- pkg/lockfile/parse-npm-lock-v2_test.go
- pkg/lockfile/parse-nuget-lock-v1_test.go
- pkg/lockfile/parse-nuget-lock_test.go
- pkg/lockfile/parse-pnpm-lock_test.go
- pkg/lockfile/parse-poetry-lock.go
- pkg/lockfile/parse-poetry-lock_test.go
- pkg/lockfile/parse-pubspec-lock_test.go
- pkg/lockfile/parse-requirements-txt_test.go
- pkg/lockfile/parse-yarn-lock-v1_test.go
- pkg/lockfile/parse-yarn-lock-v2_test.go
Per https://github.com/google/osv-scanner/pull/183/files#r1096946900
> refactor: enable `goimports` linter

- pkg/models/vulnerability_test.go
This reduces the diff with #183 a bit, and is good practice
> test: make `models` tests their own package

- CHANGELOG.md
- cmd/osv-scanner/main.go
- cmd/osv-scanner/main_test.go
> Adds changelog for v1.3.5

- .github/workflows/osv-scanner-reusable-pr.yml
> Move github action back to the main branch

- pkg/models/vulnerability.go
- pkg/models/vulnerability_test.go
> fix: ensure that "introduced 0" events are sorted before any other event

- cmd/osv-scanner/main_test.go
- internal/local/check.go
> fix: don't error if local db directory already exists

- renovate.json
Add fixtures go to renovate bot ignore
> Add fixtures go to renovate bot ignore

- renovate.json
Correctly use matchFileNames in renovate.json
> Correctly use matchFileNames in renovate.json

- CHANGELOG.md
- cmd/osv-scanner/main.go
- docs/usage.md
- pkg/lockfile/osv-vuln-results.go
- pkg/osvscanner/osvscanner.go
Changelog and version update for the 1.4.0 release.
> 1.4.0 changelog and docs

- CHANGELOG.md
Fix minor link issue in the changelog
> Fix issue in the changelog

- docs/experimental.md
This change should be in the docs branch so it will show up on our GitHub page.
> Update experimental.md (#536)

- .github/workflows/osv-scanner-reusable-pr.yml
- .github/workflows/osv-scanner-reusable-scheduled.yml
- actions/reporter/action.yml
- actions/scanner/action.yml
- cmd/osv-reporter/main.go
- cmd/osv-reporter/main_test.go
- pkg/osvscanner/optional_enricher.go
Update the github actions to pass arguments in a multi line fashion to allow much more customisability.
> Attempt at multiline action

- .github/workflows/osv-scanner-reusable-pr.yml
- .github/workflows/osv-scanner-reusable-scheduled.yml
Default's are maintained.
After this is merged we need to add more detailed documentation on how to use this as part of #516
> Add custom scan arguments

- .github/workflows/goreleaser.yml
- CHANGELOG.md
Correctly use reusable action this time.
> Fix goreleaser and update changelog

- .github/workflows/osv-scanner-reusable-pr.yml
- .github/workflows/osv-scanner-reusable.yml
- docs/github-action.md
- docs/output.md
- internal/output/fixtures/test-vuln-results-a.sarif
- internal/output/sarif_test.go
Attempt at the 3 remaining items mentioned in https://github.com/google/osv-scanner/issues/516. 
Feel free to do any rewording or rearranging @hayleycd to make things clearer!
Also fix the SARIF test since it was still calling `createTextFixture` instead of `assertTextFixture`
> Improve documentation for github actions

- .github/workflows/osv-scanner-reusable.yml
Now that #584 is merged changed branch back.
> Change branch back in github action

- docs/output.md
- docs/usage.md
- Update docs to add in saving to file option
- Fix the output page toc to not include the example's headers
> Update docs to add in saving to file option

- pkg/lockfile/fixtures/npm/alias.v1.json
- pkg/lockfile/fixtures/npm/alias.v2.json
- pkg/lockfile/parse-npm-lock-v1_test.go
- pkg/lockfile/parse-npm-lock-v2_test.go
- pkg/lockfile/parse-npm-lock.go
Fixes https://github.com/google/osv-scanner/issues/588
> handle npm aliased packages

- docs/github-action.md
Fix permissions in Github actions PR example.
> Fix permissions in PR osv-scanner

- cmd/osv-scanner/main.go
> Include available formats in `--format` help message

- .golangci.yaml
Update govet printf settings for #727
> Update govet printf settings

- docs/guided-remediation.md
Minor nit where the wording slightly confused me.
> docs: reword sentence in guided-remediation

- internal/resolution/datasource/maven_registry.go
Follow-up on https://github.com/google/osv-scanner/pull/857
> improve error messages in Maven registry client

- cmd/osv-scanner/__snapshots__/main_test.snap
- cmd/osv-scanner/main_test.go
I had not realised there were tests over here; I've included the same change in #869 for these as part of this
> test: add cli cases for `node_modules` images

- internal/remediation/relax/npm_test.go
these tests are fairly straightforward
> GR: Tests for npm relaxer

- cmd/osv-scanner/__snapshots__/main_test.snap
> Add new vuln for failing test

- internal/remediation/remediation_test.go
Basic tests for the guided remediation vulnerability filtering
> GR: Test `MatchVuln()`

- osv-scanner.toml
Until we can update to go1.21.9
> Ignore stdlib vuln

- internal/output/__snapshots__/sarif_internal_test.snap
- internal/output/fixtures/commit-grouped.json
- internal/output/sarif_internal_test.go
- internal/sourceanalysis/fixtures-go/govulncheckinput.json
Remove local paths from snapshots
> Fix paths in test snapshots

- pkg/lockfile/extract.go
I noticed this while working on other stuff 😅
> chore: add missing space to panic message

- cmd/osv-scanner/__snapshots__/main_test.snap
> Add new vuln to tests

- cmd/osv-scanner/__snapshots__/main_test.snap
Looks like this has been withdrawn
> test: update snapshots due to external vulnerability changes

- scripts/generators/GenerateMavenVersions.java
- scripts/generators/generate-debian-versions.py
- scripts/generators/generate-packagist-versions.php
- scripts/generators/generate-pypi-versions.py
- scripts/generators/generate-rubygems-versions.rb
Cherry pick of https://github.com/G-Rath/osv-detector/pull/185
> This is really all because of Maven, whose version comparison implementation is apparently pretty buggy - for now I'm going to ignore it and hope that in ~6 months when I check back on things at least some of the bugs will be fixed.
This is already included in the CRAN generator
> chore: support skipping known unsupported comparisons in generators

- scripts/generators/generate-rubygems-versions.rb
Cherry-pick of https://github.com/G-Rath/osv-detector/pull/240
---
This is all pretty harmless but there's some nice small improvements in here
> refactor: apply Rubocop to Ruby generator

- scripts/generators/generate-debian-versions.py
- scripts/generators/generate-pypi-versions.py
The irony of this is not lost on me 😅
> chore: import `sys` in Python generators

- cmd/osv-scanner/__snapshots__/main_test.snap
I wish they would stop discovering new vulnerabilities.
> Fix tests; add newly discovered vulns

- go.mod
Update to the latest go1.21 version
> Update gomod go version

- docs/installation.md
Sponsored by:	The FreeBSD Foundation
> [docs] Add installation instructions for FreeBSD and NetBSD

- CHANGELOG.md
- cmd/osv-scanner/__snapshots__/main_test.snap
- internal/output/__snapshots__/sarif_test.snap
- internal/version/version.go
> V1.7.4 changelog

- CHANGELOG.md
Remove feature from changelog as it's still blocked on #769
> Remove feature from changelog as it's still blocked on #769

- cmd/osv-scanner/__snapshots__/main_test.snap
- cmd/osv-scanner/main_test.go
This is a short-term solution to unblock the workflow.
> Update snapshots and exit codes

- .github/workflows/goreleaser.yml
- .goreleaser.yml
followup https://github.com/google/osv-scanner/pull/1052
> feat: bump goreleaser to v2

- cmd/osv-scanner/__snapshots__/main_test.snap
- internal/sourceanalysis/__snapshots__/integration_test.snap
- pkg/osvscanner/osvscanner.go
Remove redundant log messages and fix style.
> Combine Debian unimportant count logs

- docs/guided-remediation.md
I think this is the only commit that hasn't already been merged into main
> Cherry-pick unmerged change from docs branch

- cmd/osv-scanner/__snapshots__/main_test.snap
Another day, another vulnerability
> test: update snapshots

- internal/output/table.go
- internal/semantic/utilities.go
- internal/semantic/version-alpine.go
- internal/semantic/version-debian.go
- internal/semantic/version-maven.go
- internal/semantic/version-packagist.go
- internal/semantic/version-pypi.go
- internal/semantic/version-rubygems.go
- internal/semantic/version-semver.go
- internal/semantic/version.go
- pkg/grouper/grouper.go
- Changed min and max to inbuilt functions.
> Changed min and max to inbuilt functions

- internal/sbom/fixtures/spdx-empty.json
- internal/sbom/fixtures/spdx.json
- internal/sbom/spdx_test.go
- Added testing for the SPDX SBOM reader
> Added Testing for the SPDX SBOM Reader

- .github/workflows/semantic.yml
> ci: upgrade `semantic` workflow to use v4 for artifact workflows

- CHANGELOG.md
- cmd/osv-scanner/__snapshots__/main_test.snap
- cmd/osv-scanner/scan/main.go
- docs/github-action.md
- internal/output/__snapshots__/sarif_test.snap
- internal/version/version.go
> Add changelog for v1.8.2

- go.mod
Bump go mod min version to resolve vulnerability
> Bump go mod min version

- cmd/osv-scanner/__snapshots__/main_test.snap
Fix updated snapshots to make merging possible.
> Fix snapshots

- .github/workflows/staleness.yml
This way they're easily identifiable for later review
Add a nudge to encourage contribution for stale issues.
Convert message text to multiline strings for ease of future maintenance
Aggregate related configuration for ease of comprehension and future maintenance
> Label closed stale issues/PRs

- CONTRIBUTING.md
Add a conventional commit requirement to help us with changelog generation and better maintainability.
> docs: add conventional commits requirement

- .github/workflows/staleness.yml
Addresses https://github.com/google/osv-scanner/security/code-scanning/161
> fix(workflow): Add explicit permissions

- README.md
There's now a nicer UI for the Scorecard Report so link to it instead
> docs: link to the Scorecard Report

- CHANGELOG.md
- cmd/osv-scanner/__snapshots__/main_test.snap
- docs/github-action.md
- internal/output/__snapshots__/sarif_test.snap
- internal/version/version.go
> chore(release): changelog for v1.8.5

- cmd/osv-scanner/__snapshots__/main_test.snap
Just in time for some things to be landed on main 😂
> test: update snapshots with new security vulnerabilities

- cmd/osv-scanner/__snapshots__/update_test.snap
Something has changed that means this is now the test output - I assume @michaelkedar or @cuixq will sing out if its not right or means the test is invalid
> test: update snapshot

- cmd/osv-scanner/__snapshots__/main_test.snap
- cmd/osv-scanner/main_test.go
Remove all empty names in our test cases.
> refactor: Update test names

- .github/workflows/checks.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/osv-scanner-unified-action.yml
- .github/workflows/scorecards.yml
Currently we can't reliably merge into v2 because checks don't automatically trigger
> chore: Also trigger workflow when merging into v2

- CHANGELOG.md
- cmd/osv-scanner/__snapshots__/main_test.snap
- internal/output/__snapshots__/sarif_test.snap
- internal/version/version.go
changelog for v2 beta release.
> chore: v2.0.0-beta1 changelog

- docs/scan-image.md
- docs/usage.md
Linkify a discussion link, and add a link to V1 docs.
> fix: Minor docs fixes.

- docs/installation.md
> docs: Add installation instruction for WinGet users

- internal/output/html/script.js
While looking through some other stuff, I noticed my IDE had some recommendations about the JavaScript, and I spotted a few other refactors I think are worth landing, so I did a bit of a cleanup.
At a high level the changes are about being consistent and improving readability - I've purposely tried to keep this light since ultimately the amount of work being done is very small and the whole file gets included in the binary so e.g. I've not refactored the order that we set some variables even though they could be made technically faster.
Overall, this reduces the size of the file by a couple of hundred bytes which is technically a win😅
> refactor: clean up HTML js script so its more consistent

- cmd/osv-scanner/__snapshots__/main_test.snap
- internal/image/fixtures/test-java-full.Dockerfile
> chore: Pin the java image so that it can't change each build

- cmd/osv-scanner/__snapshots__/main_test.snap
> test: update snapshots again

- .github/workflows/test-action/action.yml
Let's see if things have improved since we disabled this 🤞
> ci: upload code coverage on macOS

- cmd/osv-scanner/scan/source/main.go
- docs/scan-image.md
Address comment in discussion: https://github.com/google/osv-scanner/discussions/1521#discussioncomment-12135968
> docs: Minor documentation changes

- internal/output/html.go
- internal/output/html/filter_template.gohtml
- internal/output/html/script.js
Resolves https://github.com/google/osv-scanner/issues/1665
> fix(html): show OS filter for OS lockfile scan

- cmd/osv-scanner/__snapshots__/main_test.snap
- docs/Gemfile.lock
Fix the vulnerability in docs.
> chore: Update documentation lockfile

- go.mod
- go.sum
> chore: Update osv-scalibr version

- .goreleaser.yml
I'm like 98% sure this is valid and works as we'd expect, though I'd be happier if the docs had it as an example 😅
> build: list `ldflags` as an item per flag

- .github/workflows/checks.yml
- .github/workflows/prerelease-check.yml
This should ensure this never slips through again 😄
> ci: ensure that `go.sum` is tidy

- docs/github-action.md
Fixes: https://github.com/google/osv-scanner-action/issues/68
> docs: Fix github action docs

- internal/imodels/imodels.go
- pkg/models/results.go
- pkg/osvscanner/vulnerability_result.go
> feat: Made the source type enum public

- cmd/osv-scanner/internal/helper/helper.go
- cmd/osv-scanner/scan/image/__snapshots__/command_test.snap
- internal/output/__snapshots__/output_result_test.snap
- internal/output/html.go
- internal/output/html/package_table_template.gohtml
- internal/output/output_result.go
- internal/output/table.go
- internal/output/vertical.go
Resolves https://github.com/google/osv-scanner/issues/1758
table output: 
vertical output:
HTML output:
> feat: improve OS status scanning output

- docs/configuration.md
> docs: Clarify osv-scanner.toml documentation

- internal/thirdparty/xml/marshal_test.go
- internal/thirdparty/xml/xml.go
We basically want to avoid escaping all texts...
> feat(xml): do not escape texts in char data

- cmd/osv-scanner/scan/__snapshots__/command_test.snap
- cmd/osv-scanner/scan/image/__snapshots__/command_test.snap
I am a bit confused as to why the positions of existing entries keep changing positions. Need to look into that a bit more.
> chore: Update snapshots

- cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
- cmd/osv-scanner/scan/source/command_test.go
Turns out we don't have this case covered already 🤷
> test: add case for when "false" is explicitly passed as the value for `--offline`

- cmd/osv-scanner/fix/testmain_test.go
This managed to sneak in through #1832
> test(osv-scanner/fix): actually import command from package

- goreleaser.dockerfile
> fix: setting working directory to root

- exit_code_redirect.sh
> fix(action): don't ignore general errors

- cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
- cmd/osv-scanner/scan/source/command_test.go
- cmd/osv-scanner/scan/source/fixtures/locks-scalibr/gems.locked
- docs/supported_languages_and_lockfiles.md
- pkg/osvscanner/internal/scanners/lockfile.go
This PR adds support for `gems.locked`.
> feat: Add support for gems.locked

- .golangci.yaml
- internal/resolution/manifest/maven_test.go
- internal/scalibrextract/filesystem/vendored/vendored_test.go
- internal/sourceanalysis/rust_test.go
- internal/testutility/normalize.go
- internal/testutility/utility.go
We do this enough that I think it's worth having a helper
> test: introduce helper for getting the current working directory

- .github/workflows/goreleaser-nightly.yml
Turns out the nightly config I made didn't actually use the nightly config 🤦
> fix: Go releaser nightly

- docs/Gemfile.lock
> chore: update `nokogiri` for security

- internal/clients/clientimpl/localmatcher/zip.go
> chore: remove unused function

- CHANGELOG.md
- cmd/osv-scanner/__snapshots__/main_test.snap
- cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
- docs/github-action.md
- internal/output/__snapshots__/sarif_test.snap
- internal/version/version.go
Prep changelog for 2.2.1 release on Monday
> chore: Update changelog and snapshot

- cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
- go.mod
- go.sum
- pkg/osvscanner/osvscanner.go
Fixes the breaking change in https://github.com/google/osv-scanner/pull/2147
> fix(deps): update osv-scalibr

- cmd/osv-scanner/scan/source/__snapshots__/command_test.snap
- cmd/osv-scanner/scan/source/command_test.go
> test(cmd): add case for `jar` files without call analysis

- docs/supported_languages_and_lockfiles.md
- docs/usage.md
> docs: Update documentation with fixes

- action.dockerfile
- actions/scanner/action.yml
People are getting confused which action to use. See #2194
> fix: Add warning to use the correct action

- .golangci.yaml
> chore: enable all `govet` checks by default

- cmd/osv-scanner/scan/source/testdata/artifact/osv-scanner.toml
> chore: add ignore file for javareach artifact testdata
